/**
 * Sandbox seed data — "Riverside Family Dental"
 *
 * A realistic 2-doctor general practice in Denver, CO.
 * All IDs use the 'sandbox-' prefix so they can be detected by safety guards.
 */

import type {
  Practice,
  Patient,
  Treatment,
  Sequence,
  Touchpoint,
  SequenceEnrollment,
  Message,
  Conversation,
  DashboardStats,
  ActivityItem,
  AnalyticsStats,
  ChannelBreakdownItem,
  SequenceConversionRow,
  FunnelStageItem,
} from "@/types/app.types";

// ─── Helpers ──────────────────────────────────────────────────────────────────

const now = new Date();

function daysAgo(days: number): string {
  return new Date(now.getTime() - days * 24 * 60 * 60 * 1000).toISOString();
}

function daysFromNow(days: number): string {
  return new Date(now.getTime() + days * 24 * 60 * 60 * 1000).toISOString();
}

function hoursAgo(hours: number): string {
  return new Date(now.getTime() - hours * 60 * 60 * 1000).toISOString();
}

/** Produces an S-curve daily revenue series with small random variation. */
function generateDailyRevenue(days: number): { date: string; amount: number }[] {
  const totalMax = 28450;
  const data: { date: string; amount: number }[] = [];

  for (let i = days; i >= 0; i--) {
    // S-curve: logistic function centered at days/2
    const t = (days - i) / days;
    const sigmoid = 1 / (1 + Math.exp(-10 * (t - 0.45)));
    const base = totalMax * sigmoid * (1 / days) * 2.2;
    // Add daily noise ±30%
    const noise = 0.7 + Math.random() * 0.6;
    const amount = Math.round(base * noise);

    data.push({
      date: daysAgo(i).split("T")[0],
      amount: Math.max(0, amount),
    });
  }
  return data;
}

// ─── Practice ─────────────────────────────────────────────────────────────────

export const SANDBOX_PRACTICE: Practice = {
  id: "sandbox-practice-001",
  name: "Riverside Family Dental",
  slug: "riverside-family-dental",
  phone: "(720) 555-0142",
  email: "front@riversidefamilydental.com",
  address: "4821 S Broadway, Denver, CO 80113",
  timezone: "America/Denver",
  pms_type: "open_dental",
  pms_connected: true,
  stripe_customer_id: null,
  stripe_subscription_id: null,
  subscription_status: "trialing",
  sandbox_mode: true,
  sandbox_seeded_at: daysAgo(30),
  created_at: daysAgo(30),
  updated_at: daysAgo(1),
};

// ─── Patients (20) ────────────────────────────────────────────────────────────

export const SANDBOX_PATIENTS: Patient[] = [
  // --- 8 patients with active treatment plans in sequence ---
  {
    id: "sandbox-patient-001",
    practice_id: "sandbox-practice-001",
    external_id: "OD-10421",
    first_name: "Maria",
    last_name: "Castellano",
    email: "maria.castellano@email.com",
    phone: "(720) 555-0198",
    date_of_birth: "1985-06-14",
    last_visit: daysAgo(18),
    next_appointment: null,
    status: "active",
    tags: ["preferred-sms"],
    metadata: { preferred_contact: "sms" },
    created_at: daysAgo(90),
    updated_at: daysAgo(2),
  },
  {
    id: "sandbox-patient-002",
    practice_id: "sandbox-practice-001",
    external_id: "OD-10435",
    first_name: "James",
    last_name: "Whitfield",
    email: "j.whitfield@gmail.com",
    phone: "(303) 555-0271",
    date_of_birth: "1972-11-03",
    last_visit: daysAgo(25),
    next_appointment: null,
    status: "active",
    tags: ["preferred-email"],
    metadata: { preferred_contact: "email" },
    created_at: daysAgo(120),
    updated_at: daysAgo(5),
  },
  {
    id: "sandbox-patient-003",
    practice_id: "sandbox-practice-001",
    external_id: "OD-10448",
    first_name: "Priya",
    last_name: "Nair",
    email: "priya.n@outlook.com",
    phone: "(720) 555-0334",
    date_of_birth: "1993-02-28",
    last_visit: daysAgo(12),
    next_appointment: null,
    status: "active",
    tags: ["preferred-sms"],
    metadata: { preferred_contact: "sms" },
    created_at: daysAgo(60),
    updated_at: daysAgo(1),
  },
  {
    id: "sandbox-patient-004",
    practice_id: "sandbox-practice-001",
    external_id: "OD-10462",
    first_name: "David",
    last_name: "Kowalski",
    email: "dkowalski@yahoo.com",
    phone: "(303) 555-0419",
    date_of_birth: "1968-08-19",
    last_visit: daysAgo(30),
    next_appointment: null,
    status: "active",
    tags: ["preferred-sms"],
    metadata: { preferred_contact: "sms" },
    created_at: daysAgo(200),
    updated_at: daysAgo(8),
  },
  {
    id: "sandbox-patient-005",
    practice_id: "sandbox-practice-001",
    external_id: "OD-10479",
    first_name: "Sarah",
    last_name: "Okonkwo",
    email: "sokonkwo@email.com",
    phone: "(720) 555-0587",
    date_of_birth: "1990-04-22",
    last_visit: daysAgo(14),
    next_appointment: null,
    status: "active",
    tags: ["preferred-email"],
    metadata: { preferred_contact: "email" },
    created_at: daysAgo(75),
    updated_at: daysAgo(3),
  },
  {
    id: "sandbox-patient-006",
    practice_id: "sandbox-practice-001",
    external_id: "OD-10503",
    first_name: "Carlos",
    last_name: "Mendoza",
    email: "carlos.m@email.com",
    phone: "(303) 555-0623",
    date_of_birth: "1979-12-01",
    last_visit: daysAgo(20),
    next_appointment: null,
    status: "active",
    tags: ["preferred-sms", "spanish"],
    metadata: { preferred_contact: "sms", language: "es" },
    created_at: daysAgo(150),
    updated_at: daysAgo(6),
  },
  {
    id: "sandbox-patient-007",
    practice_id: "sandbox-practice-001",
    external_id: "OD-10518",
    first_name: "Emily",
    last_name: "Thornton",
    email: "ethornton@gmail.com",
    phone: "(720) 555-0741",
    date_of_birth: "1995-07-10",
    last_visit: daysAgo(10),
    next_appointment: null,
    status: "active",
    tags: ["preferred-sms"],
    metadata: { preferred_contact: "sms" },
    created_at: daysAgo(45),
    updated_at: daysAgo(4),
  },
  {
    id: "sandbox-patient-008",
    practice_id: "sandbox-practice-001",
    external_id: "OD-10531",
    first_name: "Robert",
    last_name: "Chen",
    email: "rob.chen@email.com",
    phone: "(303) 555-0856",
    date_of_birth: "1960-03-15",
    last_visit: daysAgo(22),
    next_appointment: null,
    status: "active",
    tags: ["preferred-email"],
    metadata: { preferred_contact: "email" },
    created_at: daysAgo(180),
    updated_at: daysAgo(7),
  },

  // --- 4 patients with pending plans (not yet in sequence) ---
  {
    id: "sandbox-patient-009",
    practice_id: "sandbox-practice-001",
    external_id: "OD-10547",
    first_name: "Angela",
    last_name: "Rivera",
    email: "angela.r@outlook.com",
    phone: "(720) 555-0912",
    date_of_birth: "1988-09-05",
    last_visit: daysAgo(7),
    next_appointment: null,
    status: "active",
    tags: ["preferred-sms"],
    metadata: { preferred_contact: "sms" },
    created_at: daysAgo(30),
    updated_at: daysAgo(7),
  },
  {
    id: "sandbox-patient-010",
    practice_id: "sandbox-practice-001",
    external_id: "OD-10559",
    first_name: "Marcus",
    last_name: "Johnson",
    email: "marcus.j@gmail.com",
    phone: "(303) 555-1034",
    date_of_birth: "1975-01-20",
    last_visit: daysAgo(5),
    next_appointment: null,
    status: "active",
    tags: ["preferred-sms"],
    metadata: { preferred_contact: "sms" },
    created_at: daysAgo(95),
    updated_at: daysAgo(5),
  },
  {
    id: "sandbox-patient-011",
    practice_id: "sandbox-practice-001",
    external_id: "OD-10572",
    first_name: "Lisa",
    last_name: "Patel",
    email: "lisa.patel@email.com",
    phone: "(720) 555-1148",
    date_of_birth: "1991-05-30",
    last_visit: daysAgo(3),
    next_appointment: null,
    status: "active",
    tags: ["preferred-email"],
    metadata: { preferred_contact: "email" },
    created_at: daysAgo(40),
    updated_at: daysAgo(3),
  },
  {
    id: "sandbox-patient-012",
    practice_id: "sandbox-practice-001",
    external_id: "OD-10588",
    first_name: "Tyler",
    last_name: "Bergstrom",
    email: "tbergstrom@yahoo.com",
    phone: "(303) 555-1267",
    date_of_birth: "1983-10-12",
    last_visit: daysAgo(4),
    next_appointment: null,
    status: "active",
    tags: ["preferred-sms"],
    metadata: { preferred_contact: "sms" },
    created_at: daysAgo(110),
    updated_at: daysAgo(4),
  },

  // --- 3 patients who booked after a sequence (success stories) ---
  {
    id: "sandbox-patient-013",
    practice_id: "sandbox-practice-001",
    external_id: "OD-10301",
    first_name: "Jennifer",
    last_name: "Hawkins",
    email: "jhawkins@email.com",
    phone: "(720) 555-1389",
    date_of_birth: "1987-03-25",
    last_visit: daysAgo(8),
    next_appointment: daysFromNow(5),
    status: "active",
    tags: ["converted"],
    metadata: { preferred_contact: "sms" },
    created_at: daysAgo(160),
    updated_at: daysAgo(8),
  },
  {
    id: "sandbox-patient-014",
    practice_id: "sandbox-practice-001",
    external_id: "OD-10315",
    first_name: "Michael",
    last_name: "Torres",
    email: "mtorres@gmail.com",
    phone: "(303) 555-1456",
    date_of_birth: "1970-07-08",
    last_visit: daysAgo(12),
    next_appointment: daysFromNow(2),
    status: "active",
    tags: ["converted"],
    metadata: { preferred_contact: "email" },
    created_at: daysAgo(200),
    updated_at: daysAgo(6),
  },
  {
    id: "sandbox-patient-015",
    practice_id: "sandbox-practice-001",
    external_id: "OD-10328",
    first_name: "Amara",
    last_name: "Diallo",
    email: "amara.d@outlook.com",
    phone: "(720) 555-1523",
    date_of_birth: "1996-11-17",
    last_visit: daysAgo(6),
    next_appointment: daysFromNow(8),
    status: "active",
    tags: ["converted"],
    metadata: { preferred_contact: "sms" },
    created_at: daysAgo(50),
    updated_at: daysAgo(4),
  },

  // --- 3 patients with no active plans ---
  {
    id: "sandbox-patient-016",
    practice_id: "sandbox-practice-001",
    external_id: "OD-10210",
    first_name: "Kevin",
    last_name: "Brandt",
    email: "kbrandt@email.com",
    phone: "(303) 555-1678",
    date_of_birth: "1965-04-02",
    last_visit: daysAgo(45),
    next_appointment: null,
    status: "active",
    tags: [],
    metadata: {},
    created_at: daysAgo(300),
    updated_at: daysAgo(45),
  },
  {
    id: "sandbox-patient-017",
    practice_id: "sandbox-practice-001",
    external_id: "OD-10225",
    first_name: "Stephanie",
    last_name: "Nguyen",
    email: "steph.nguyen@gmail.com",
    phone: "(720) 555-1794",
    date_of_birth: "1999-08-21",
    last_visit: daysAgo(60),
    next_appointment: null,
    status: "active",
    tags: [],
    metadata: {},
    created_at: daysAgo(250),
    updated_at: daysAgo(60),
  },
  {
    id: "sandbox-patient-018",
    practice_id: "sandbox-practice-001",
    external_id: "OD-10240",
    first_name: "Brian",
    last_name: "Olsen",
    email: "bolsen@yahoo.com",
    phone: "(303) 555-1901",
    date_of_birth: "1982-12-30",
    last_visit: daysAgo(90),
    next_appointment: null,
    status: "inactive",
    tags: [],
    metadata: {},
    created_at: daysAgo(400),
    updated_at: daysAgo(90),
  },

  // --- 2 patients marked do-not-contact ---
  {
    id: "sandbox-patient-019",
    practice_id: "sandbox-practice-001",
    external_id: "OD-10255",
    first_name: "Patricia",
    last_name: "Fleming",
    email: "pfleming@email.com",
    phone: "(720) 555-2018",
    date_of_birth: "1958-02-14",
    last_visit: daysAgo(35),
    next_appointment: null,
    status: "archived",
    tags: ["do-not-contact"],
    metadata: { dnc_reason: "Patient requested no further outreach" },
    created_at: daysAgo(350),
    updated_at: daysAgo(20),
  },
  {
    id: "sandbox-patient-020",
    practice_id: "sandbox-practice-001",
    external_id: "OD-10268",
    first_name: "Raymond",
    last_name: "Gutierrez",
    email: "rgutierrez@outlook.com",
    phone: "(303) 555-2135",
    date_of_birth: "1974-06-09",
    last_visit: daysAgo(50),
    next_appointment: null,
    status: "archived",
    tags: ["do-not-contact"],
    metadata: { dnc_reason: "Replied STOP to SMS" },
    created_at: daysAgo(280),
    updated_at: daysAgo(15),
  },
];

// ─── Treatments (15) ──────────────────────────────────────────────────────────

export const SANDBOX_TREATMENTS: Treatment[] = [
  // Active plans in sequence (patients 001-008)
  {
    id: "sandbox-treatment-001",
    practice_id: "sandbox-practice-001",
    patient_id: "sandbox-patient-001",
    code: "D2740",
    description: "Crown — upper left molar (#14)",
    amount: 1450,
    status: "pending",
    presented_at: daysAgo(18),
    decided_at: null,
    created_at: daysAgo(18),
    updated_at: daysAgo(2),
  },
  {
    id: "sandbox-treatment-002",
    practice_id: "sandbox-practice-001",
    patient_id: "sandbox-patient-002",
    code: "D6010",
    description: "Implant placement and crown — lower left (#19)",
    amount: 3800,
    status: "pending",
    presented_at: daysAgo(25),
    decided_at: null,
    created_at: daysAgo(25),
    updated_at: daysAgo(5),
  },
  {
    id: "sandbox-treatment-003",
    practice_id: "sandbox-practice-001",
    patient_id: "sandbox-patient-003",
    code: "D2392",
    description: "Two-surface composite — #19 mesial-occlusal",
    amount: 285,
    status: "pending",
    presented_at: daysAgo(12),
    decided_at: null,
    created_at: daysAgo(12),
    updated_at: daysAgo(1),
  },
  {
    id: "sandbox-treatment-004",
    practice_id: "sandbox-practice-001",
    patient_id: "sandbox-patient-004",
    code: "D4341",
    description: "Full upper arch deep cleaning (SRP)",
    amount: 480,
    status: "pending",
    presented_at: daysAgo(30),
    decided_at: null,
    created_at: daysAgo(30),
    updated_at: daysAgo(8),
  },
  {
    id: "sandbox-treatment-005",
    practice_id: "sandbox-practice-001",
    patient_id: "sandbox-patient-005",
    code: "D2960",
    description: "Composite veneer — upper front four (#7–10)",
    amount: 2400,
    status: "pending",
    presented_at: daysAgo(14),
    decided_at: null,
    created_at: daysAgo(14),
    updated_at: daysAgo(3),
  },
  {
    id: "sandbox-treatment-006",
    practice_id: "sandbox-practice-001",
    patient_id: "sandbox-patient-006",
    code: "D6240",
    description: "Three-unit bridge — #28–30",
    amount: 3200,
    status: "pending",
    presented_at: daysAgo(20),
    decided_at: null,
    created_at: daysAgo(20),
    updated_at: daysAgo(6),
  },
  {
    id: "sandbox-treatment-007",
    practice_id: "sandbox-practice-001",
    patient_id: "sandbox-patient-007",
    code: "D3330",
    description: "Root canal — lower right premolar (#28)",
    amount: 1200,
    status: "pending",
    presented_at: daysAgo(10),
    decided_at: null,
    created_at: daysAgo(10),
    updated_at: daysAgo(4),
  },
  {
    id: "sandbox-treatment-008",
    practice_id: "sandbox-practice-001",
    patient_id: "sandbox-patient-008",
    code: "D7210",
    description: "Extraction and socket preservation — #17",
    amount: 650,
    status: "pending",
    presented_at: daysAgo(22),
    decided_at: null,
    created_at: daysAgo(22),
    updated_at: daysAgo(7),
  },

  // Pending plans not yet in sequence (patients 009-012)
  {
    id: "sandbox-treatment-009",
    practice_id: "sandbox-practice-001",
    patient_id: "sandbox-patient-009",
    code: "D2740",
    description: "Crown — lower right molar (#30)",
    amount: 1450,
    status: "pending",
    presented_at: daysAgo(7),
    decided_at: null,
    created_at: daysAgo(7),
    updated_at: daysAgo(7),
  },
  {
    id: "sandbox-treatment-010",
    practice_id: "sandbox-practice-001",
    patient_id: "sandbox-patient-010",
    code: "D6010",
    description: "Implant placement — upper right (#3)",
    amount: 3800,
    status: "pending",
    presented_at: daysAgo(5),
    decided_at: null,
    created_at: daysAgo(5),
    updated_at: daysAgo(5),
  },
  {
    id: "sandbox-treatment-011",
    practice_id: "sandbox-practice-001",
    patient_id: "sandbox-patient-011",
    code: "D2392",
    description: "Two-surface composite — #12 distal-occlusal",
    amount: 285,
    status: "pending",
    presented_at: daysAgo(3),
    decided_at: null,
    created_at: daysAgo(3),
    updated_at: daysAgo(3),
  },
  {
    id: "sandbox-treatment-012",
    practice_id: "sandbox-practice-001",
    patient_id: "sandbox-patient-012",
    code: "D4341",
    description: "Full lower arch deep cleaning (SRP)",
    amount: 480,
    status: "pending",
    presented_at: daysAgo(4),
    decided_at: null,
    created_at: daysAgo(4),
    updated_at: daysAgo(4),
  },

  // Booked / completed plans (patients 013-015) — the success stories
  {
    id: "sandbox-treatment-013",
    practice_id: "sandbox-practice-001",
    patient_id: "sandbox-patient-013",
    code: "D2740",
    description: "Crown — upper right premolar (#4)",
    amount: 1450,
    status: "accepted",
    presented_at: daysAgo(35),
    decided_at: daysAgo(8),
    created_at: daysAgo(35),
    updated_at: daysAgo(8),
  },
  {
    id: "sandbox-treatment-014",
    practice_id: "sandbox-practice-001",
    patient_id: "sandbox-patient-014",
    code: "D6065",
    description: "Implant crown — lower left (#19)",
    amount: 3800,
    status: "accepted",
    presented_at: daysAgo(40),
    decided_at: daysAgo(12),
    created_at: daysAgo(40),
    updated_at: daysAgo(6),
  },
  {
    id: "sandbox-treatment-015",
    practice_id: "sandbox-practice-001",
    patient_id: "sandbox-patient-015",
    code: "D7210",
    description: "Extraction — upper left wisdom (#16)",
    amount: 650,
    status: "accepted",
    presented_at: daysAgo(28),
    decided_at: daysAgo(6),
    created_at: daysAgo(28),
    updated_at: daysAgo(4),
  },
];

// ─── Sequences (3) ────────────────────────────────────────────────────────────

export const SANDBOX_SEQUENCES: Sequence[] = [
  {
    id: "sandbox-sequence-001",
    practice_id: "sandbox-practice-001",
    name: "Standard Crown & Restorative",
    description: "For crown, bridge, and multi-surface composite plans",
    treatment_type: "D2740,D2392,D6240",
    status: "active",
    trigger_type: "treatment_declined",
    patient_count: 12,
    conversion_rate: 37.5,
    created_at: daysAgo(28),
    updated_at: daysAgo(2),
  },
  {
    id: "sandbox-sequence-002",
    practice_id: "sandbox-practice-001",
    name: "High-Value Implant & Prosthetic",
    description: "For implant, full arch, and cosmetic cases over $2,000",
    treatment_type: "D6010,D6065,D2960",
    status: "active",
    trigger_type: "treatment_declined",
    patient_count: 8,
    conversion_rate: 45.4,
    created_at: daysAgo(28),
    updated_at: daysAgo(3),
  },
  {
    id: "sandbox-sequence-003",
    practice_id: "sandbox-practice-001",
    name: "Perio & Preventive Follow-Up",
    description: "For SRP, extraction, and hygiene treatment plans",
    treatment_type: "D4341,D7210,D7953",
    status: "active",
    trigger_type: "treatment_declined",
    patient_count: 6,
    conversion_rate: 22.2,
    created_at: daysAgo(28),
    updated_at: daysAgo(5),
  },
];

// ─── Touchpoints (9 total across 3 sequences) ────────────────────────────────

export const SANDBOX_TOUCHPOINTS: Touchpoint[] = [
  // Sequence 1: Standard Crown & Restorative — 3 steps
  {
    id: "sandbox-touchpoint-001",
    sequence_id: "sandbox-sequence-001",
    position: 1,
    channel: "sms",
    delay_days: 3,
    delay_hours: 0,
    subject: null,
    body_template:
      "Hi {{first_name}}, this is Riverside Family Dental. You have a treatment plan ready to schedule. View details and book here: {{portal_link}}",
    ai_personalize: true,
    created_at: daysAgo(28),
    updated_at: daysAgo(28),
  },
  {
    id: "sandbox-touchpoint-002",
    sequence_id: "sandbox-sequence-001",
    position: 2,
    channel: "email",
    delay_days: 10,
    delay_hours: 0,
    subject: "Your treatment plan at Riverside Family Dental",
    body_template:
      "Dear {{first_name}},\n\nDr. Anderson wanted to follow up on the treatment plan we discussed during your last visit. Completing this treatment is important for your long-term oral health.\n\nYou can view your plan details and schedule your appointment here:\n{{portal_link}}\n\nWe have several openings this month and can work with your schedule. If cost is a concern, we also offer flexible payment plans.\n\nBest regards,\nRiverside Family Dental",
    ai_personalize: true,
    created_at: daysAgo(28),
    updated_at: daysAgo(28),
  },
  {
    id: "sandbox-touchpoint-003",
    sequence_id: "sandbox-sequence-001",
    position: 3,
    channel: "voicemail",
    delay_days: 21,
    delay_hours: 0,
    subject: null,
    body_template:
      "Hi {{first_name}}, this is a friendly reminder from Riverside Family Dental about your treatment plan. We want to make sure you get the care you need. Check your text or email for a secure link to view your plan, or give us a call at (720) 555-0142. Have a great day!",
    ai_personalize: false,
    created_at: daysAgo(28),
    updated_at: daysAgo(28),
  },

  // Sequence 2: High-Value Implant & Prosthetic — 4 steps
  {
    id: "sandbox-touchpoint-004",
    sequence_id: "sandbox-sequence-002",
    position: 1,
    channel: "sms",
    delay_days: 2,
    delay_hours: 0,
    subject: null,
    body_template:
      "Hi {{first_name}}! This is Riverside Family Dental. Just following up on your treatment plan. View your plan details here: {{portal_link}} — happy to answer any questions. Text back or call (720) 555-0142.",
    ai_personalize: true,
    created_at: daysAgo(28),
    updated_at: daysAgo(28),
  },
  {
    id: "sandbox-touchpoint-005",
    sequence_id: "sandbox-sequence-002",
    position: 2,
    channel: "email",
    delay_days: 7,
    delay_hours: 0,
    subject: "Important information about your treatment plan",
    body_template:
      "Dear {{first_name}},\n\nDr. Anderson wanted to share some additional information about your treatment plan that may help with your decision.\n\nYou can review your full plan details here:\n{{portal_link}}\n\nWe offer financing options through CareCredit to help make treatment affordable. We'd love to answer any questions you have — please don't hesitate to reach out.\n\nWarm regards,\nRiverside Family Dental",
    ai_personalize: true,
    created_at: daysAgo(28),
    updated_at: daysAgo(28),
  },
  {
    id: "sandbox-touchpoint-006",
    sequence_id: "sandbox-sequence-002",
    position: 3,
    channel: "sms",
    delay_days: 14,
    delay_hours: 0,
    subject: null,
    body_template:
      "{{first_name}}, quick reminder from Riverside Family Dental — you have a treatment plan ready to schedule. We have limited openings this month. View your plan: {{portal_link}} — Reply YES to reserve a spot.",
    ai_personalize: true,
    created_at: daysAgo(28),
    updated_at: daysAgo(28),
  },
  {
    id: "sandbox-touchpoint-007",
    sequence_id: "sandbox-sequence-002",
    position: 4,
    channel: "voicemail",
    delay_days: 30,
    delay_hours: 0,
    subject: null,
    body_template:
      "Hi {{first_name}}, this is Riverside Family Dental reaching out one more time about your treatment plan. We care about your health and want to make sure you have everything you need. Check your text or email for a secure link to view your plan, or call us at (720) 555-0142. Take care!",
    ai_personalize: false,
    created_at: daysAgo(28),
    updated_at: daysAgo(28),
  },

  // Sequence 3: Perio & Preventive Follow-Up — 2 steps
  {
    id: "sandbox-touchpoint-008",
    sequence_id: "sandbox-sequence-003",
    position: 1,
    channel: "sms",
    delay_days: 5,
    delay_hours: 0,
    subject: null,
    body_template:
      "Hi {{first_name}}, Riverside Family Dental here. We wanted to check in about the treatment plan from your recent visit. View your plan and schedule here: {{portal_link}}",
    ai_personalize: true,
    created_at: daysAgo(28),
    updated_at: daysAgo(28),
  },
  {
    id: "sandbox-touchpoint-009",
    sequence_id: "sandbox-sequence-003",
    position: 2,
    channel: "email",
    delay_days: 15,
    delay_hours: 0,
    subject: "Follow-up: Your recommended treatment",
    body_template:
      "Dear {{first_name}},\n\nWe're reaching out about the treatment plan from your last visit. This treatment plays an important role in maintaining your oral health.\n\nYou can view your plan details and schedule here:\n{{portal_link}}\n\nWe have availability this week and next. Please reply or call (720) 555-0142 to schedule.\n\nThank you,\nRiverside Family Dental",
    ai_personalize: true,
    created_at: daysAgo(28),
    updated_at: daysAgo(28),
  },
];

// ─── Sequence Enrollments (11) ────────────────────────────────────────────────

export const SANDBOX_ENROLLMENTS: SequenceEnrollment[] = [
  // 8 active enrollments (patients 001-008)
  {
    id: "sandbox-enrollment-001",
    sequence_id: "sandbox-sequence-001",
    patient_id: "sandbox-patient-001",
    practice_id: "sandbox-practice-001",
    status: "active",
    current_touchpoint: 2,
    enrolled_at: daysAgo(15),
    completed_at: null,
    converted_at: null,
  },
  {
    id: "sandbox-enrollment-002",
    sequence_id: "sandbox-sequence-002",
    patient_id: "sandbox-patient-002",
    practice_id: "sandbox-practice-001",
    status: "active",
    current_touchpoint: 3,
    enrolled_at: daysAgo(20),
    completed_at: null,
    converted_at: null,
  },
  {
    id: "sandbox-enrollment-003",
    sequence_id: "sandbox-sequence-001",
    patient_id: "sandbox-patient-003",
    practice_id: "sandbox-practice-001",
    status: "active",
    current_touchpoint: 1,
    enrolled_at: daysAgo(8),
    completed_at: null,
    converted_at: null,
  },
  {
    id: "sandbox-enrollment-004",
    sequence_id: "sandbox-sequence-003",
    patient_id: "sandbox-patient-004",
    practice_id: "sandbox-practice-001",
    status: "active",
    current_touchpoint: 2,
    enrolled_at: daysAgo(22),
    completed_at: null,
    converted_at: null,
  },
  {
    id: "sandbox-enrollment-005",
    sequence_id: "sandbox-sequence-002",
    patient_id: "sandbox-patient-005",
    practice_id: "sandbox-practice-001",
    status: "active",
    current_touchpoint: 2,
    enrolled_at: daysAgo(10),
    completed_at: null,
    converted_at: null,
  },
  {
    id: "sandbox-enrollment-006",
    sequence_id: "sandbox-sequence-001",
    patient_id: "sandbox-patient-006",
    practice_id: "sandbox-practice-001",
    status: "active",
    current_touchpoint: 2,
    enrolled_at: daysAgo(16),
    completed_at: null,
    converted_at: null,
  },
  {
    id: "sandbox-enrollment-007",
    sequence_id: "sandbox-sequence-001",
    patient_id: "sandbox-patient-007",
    practice_id: "sandbox-practice-001",
    status: "active",
    current_touchpoint: 1,
    enrolled_at: daysAgo(6),
    completed_at: null,
    converted_at: null,
  },
  {
    id: "sandbox-enrollment-008",
    sequence_id: "sandbox-sequence-003",
    patient_id: "sandbox-patient-008",
    practice_id: "sandbox-practice-001",
    status: "active",
    current_touchpoint: 1,
    enrolled_at: daysAgo(14),
    completed_at: null,
    converted_at: null,
  },

  // 3 converted enrollments (patients 013-015 — success stories)
  {
    id: "sandbox-enrollment-009",
    sequence_id: "sandbox-sequence-001",
    patient_id: "sandbox-patient-013",
    practice_id: "sandbox-practice-001",
    status: "converted",
    current_touchpoint: 2,
    enrolled_at: daysAgo(30),
    completed_at: null,
    converted_at: daysAgo(8),
  },
  {
    id: "sandbox-enrollment-010",
    sequence_id: "sandbox-sequence-002",
    patient_id: "sandbox-patient-014",
    practice_id: "sandbox-practice-001",
    status: "converted",
    current_touchpoint: 3,
    enrolled_at: daysAgo(35),
    completed_at: null,
    converted_at: daysAgo(12),
  },
  {
    id: "sandbox-enrollment-011",
    sequence_id: "sandbox-sequence-003",
    patient_id: "sandbox-patient-015",
    practice_id: "sandbox-practice-001",
    status: "converted",
    current_touchpoint: 1,
    enrolled_at: daysAgo(20),
    completed_at: null,
    converted_at: daysAgo(6),
  },
];

// ─── Messages (40+) ──────────────────────────────────────────────────────────

export const SANDBOX_MESSAGES: Message[] = [
  // --- Outbound messages for patient 001 (Maria Castellano) — Crown sequence ---
  {
    id: "sandbox-message-001",
    practice_id: "sandbox-practice-001",
    patient_id: "sandbox-patient-001",
    enrollment_id: "sandbox-enrollment-001",
    touchpoint_id: "sandbox-touchpoint-001",
    channel: "sms",
    direction: "outbound",
    status: "delivered",
    subject: null,
    body: "Hi Maria, this is Riverside Family Dental. You have a treatment plan ready to schedule. View details and book here: https://followdent.com/portal/t/abc123",
    external_id: "sandbox-sms-ext-001",
    error: null,
    sent_at: daysAgo(12),
    delivered_at: daysAgo(12),
    read_at: null,
    created_at: daysAgo(12),
  },
  {
    id: "sandbox-message-002",
    practice_id: "sandbox-practice-001",
    patient_id: "sandbox-patient-001",
    enrollment_id: "sandbox-enrollment-001",
    touchpoint_id: "sandbox-touchpoint-002",
    channel: "email",
    direction: "outbound",
    status: "delivered",
    subject: "Your treatment plan at Riverside Family Dental",
    body: "Dear Maria,\n\nDr. Anderson wanted to follow up on the treatment plan we discussed during your last visit. Completing this treatment is important for your long-term oral health.\n\nYou can view your plan details and schedule your appointment here:\nhttps://followdent.com/portal/t/def456\n\nWe have several openings this month and can work with your schedule. If cost is a concern, we also offer flexible payment plans.\n\nBest regards,\nRiverside Family Dental",
    external_id: "sandbox-email-ext-001",
    error: null,
    sent_at: daysAgo(5),
    delivered_at: daysAgo(5),
    read_at: daysAgo(4),
    created_at: daysAgo(5),
  },
  // Inbound reply from Maria
  {
    id: "sandbox-message-003",
    practice_id: "sandbox-practice-001",
    patient_id: "sandbox-patient-001",
    enrollment_id: "sandbox-enrollment-001",
    touchpoint_id: null,
    channel: "sms",
    direction: "inbound",
    status: "received",
    subject: null,
    body: "Hi yes I would like to schedule, what times do you have?",
    external_id: "sandbox-sms-ext-002",
    error: null,
    sent_at: null,
    delivered_at: null,
    read_at: null,
    created_at: daysAgo(2),
  },

  // --- Outbound messages for patient 002 (James Whitfield) — Implant sequence ---
  {
    id: "sandbox-message-004",
    practice_id: "sandbox-practice-001",
    patient_id: "sandbox-patient-002",
    enrollment_id: "sandbox-enrollment-002",
    touchpoint_id: "sandbox-touchpoint-004",
    channel: "sms",
    direction: "outbound",
    status: "delivered",
    subject: null,
    body: "Hi James! This is Riverside Family Dental. Just following up on your treatment plan. View your plan details here: https://followdent.com/portal/t/ghi789 — happy to answer any questions. Text back or call (720) 555-0142.",
    external_id: "sandbox-sms-ext-003",
    error: null,
    sent_at: daysAgo(18),
    delivered_at: daysAgo(18),
    read_at: null,
    created_at: daysAgo(18),
  },
  {
    id: "sandbox-message-005",
    practice_id: "sandbox-practice-001",
    patient_id: "sandbox-patient-002",
    enrollment_id: "sandbox-enrollment-002",
    touchpoint_id: "sandbox-touchpoint-005",
    channel: "email",
    direction: "outbound",
    status: "delivered",
    subject: "Important information about your treatment plan",
    body: "Dear James,\n\nDr. Anderson wanted to share some additional information about your treatment plan that may help with your decision.\n\nYou can review your full plan details here:\nhttps://followdent.com/portal/t/jkl012\n\nWe offer financing options through CareCredit to help make treatment affordable. We'd love to answer any questions you have — please don't hesitate to reach out.\n\nWarm regards,\nRiverside Family Dental",
    external_id: "sandbox-email-ext-002",
    error: null,
    sent_at: daysAgo(13),
    delivered_at: daysAgo(13),
    read_at: daysAgo(12),
    created_at: daysAgo(13),
  },
  {
    id: "sandbox-message-006",
    practice_id: "sandbox-practice-001",
    patient_id: "sandbox-patient-002",
    enrollment_id: "sandbox-enrollment-002",
    touchpoint_id: "sandbox-touchpoint-006",
    channel: "sms",
    direction: "outbound",
    status: "delivered",
    subject: null,
    body: "James, quick reminder from Riverside Family Dental — you have a treatment plan ready to schedule. We have limited openings this month. View your plan: https://followdent.com/portal/t/mno345 — Reply YES to reserve a spot.",
    external_id: "sandbox-sms-ext-004",
    error: null,
    sent_at: daysAgo(6),
    delivered_at: daysAgo(6),
    read_at: null,
    created_at: daysAgo(6),
  },
  // Inbound reply from James
  {
    id: "sandbox-message-007",
    practice_id: "sandbox-practice-001",
    patient_id: "sandbox-patient-002",
    enrollment_id: "sandbox-enrollment-002",
    touchpoint_id: null,
    channel: "sms",
    direction: "inbound",
    status: "received",
    subject: null,
    body: "Can you call me instead? I prefer to talk on the phone.",
    external_id: "sandbox-sms-ext-005",
    error: null,
    sent_at: null,
    delivered_at: null,
    read_at: null,
    created_at: daysAgo(5),
  },

  // --- Outbound messages for patient 003 (Priya Nair) — Crown sequence ---
  {
    id: "sandbox-message-008",
    practice_id: "sandbox-practice-001",
    patient_id: "sandbox-patient-003",
    enrollment_id: "sandbox-enrollment-003",
    touchpoint_id: "sandbox-touchpoint-001",
    channel: "sms",
    direction: "outbound",
    status: "delivered",
    subject: null,
    body: "Hi Priya, this is Riverside Family Dental. You have a treatment plan ready to schedule. View details and book here: https://followdent.com/portal/t/pqr678",
    external_id: "sandbox-sms-ext-006",
    error: null,
    sent_at: daysAgo(5),
    delivered_at: daysAgo(5),
    read_at: null,
    created_at: daysAgo(5),
  },
  // Inbound reply from Priya
  {
    id: "sandbox-message-009",
    practice_id: "sandbox-practice-001",
    patient_id: "sandbox-patient-003",
    enrollment_id: "sandbox-enrollment-003",
    touchpoint_id: null,
    channel: "sms",
    direction: "inbound",
    status: "received",
    subject: null,
    body: "Yes! Book me in please \u{1F642}",
    external_id: "sandbox-sms-ext-007",
    error: null,
    sent_at: null,
    delivered_at: null,
    read_at: null,
    created_at: daysAgo(1),
  },

  // --- Outbound messages for patient 004 (David Kowalski) — Perio sequence ---
  {
    id: "sandbox-message-010",
    practice_id: "sandbox-practice-001",
    patient_id: "sandbox-patient-004",
    enrollment_id: "sandbox-enrollment-004",
    touchpoint_id: "sandbox-touchpoint-008",
    channel: "sms",
    direction: "outbound",
    status: "delivered",
    subject: null,
    body: "Hi David, Riverside Family Dental here. We wanted to check in about the treatment plan from your recent visit. View your plan and schedule here: https://followdent.com/portal/t/stu901",
    external_id: "sandbox-sms-ext-008",
    error: null,
    sent_at: daysAgo(17),
    delivered_at: daysAgo(17),
    read_at: null,
    created_at: daysAgo(17),
  },
  {
    id: "sandbox-message-011",
    practice_id: "sandbox-practice-001",
    patient_id: "sandbox-patient-004",
    enrollment_id: "sandbox-enrollment-004",
    touchpoint_id: "sandbox-touchpoint-009",
    channel: "email",
    direction: "outbound",
    status: "delivered",
    subject: "Follow-up: Your recommended treatment",
    body: "Dear David,\n\nWe're reaching out about the treatment plan from your last visit. This treatment plays an important role in maintaining your oral health.\n\nYou can view your plan details and schedule here:\nhttps://followdent.com/portal/t/vwx234\n\nWe have availability this week and next. Please reply or call (720) 555-0142 to schedule.\n\nThank you,\nRiverside Family Dental",
    external_id: "sandbox-email-ext-003",
    error: null,
    sent_at: daysAgo(7),
    delivered_at: daysAgo(7),
    read_at: null,
    created_at: daysAgo(7),
  },
  // Inbound reply from David
  {
    id: "sandbox-message-012",
    practice_id: "sandbox-practice-001",
    patient_id: "sandbox-patient-004",
    enrollment_id: "sandbox-enrollment-004",
    touchpoint_id: null,
    channel: "sms",
    direction: "inbound",
    status: "received",
    subject: null,
    body: "Not right now, maybe next month",
    external_id: "sandbox-sms-ext-009",
    error: null,
    sent_at: null,
    delivered_at: null,
    read_at: null,
    created_at: daysAgo(8),
  },

  // --- Outbound messages for patient 005 (Sarah Okonkwo) — Implant sequence ---
  {
    id: "sandbox-message-013",
    practice_id: "sandbox-practice-001",
    patient_id: "sandbox-patient-005",
    enrollment_id: "sandbox-enrollment-005",
    touchpoint_id: "sandbox-touchpoint-004",
    channel: "sms",
    direction: "outbound",
    status: "delivered",
    subject: null,
    body: "Hi Sarah! This is Riverside Family Dental. Just following up on your treatment plan. View your plan details here: https://followdent.com/portal/t/yza567 — happy to answer any questions. Text back or call (720) 555-0142.",
    external_id: "sandbox-sms-ext-010",
    error: null,
    sent_at: daysAgo(8),
    delivered_at: daysAgo(8),
    read_at: null,
    created_at: daysAgo(8),
  },
  {
    id: "sandbox-message-014",
    practice_id: "sandbox-practice-001",
    patient_id: "sandbox-patient-005",
    enrollment_id: "sandbox-enrollment-005",
    touchpoint_id: "sandbox-touchpoint-005",
    channel: "email",
    direction: "outbound",
    status: "delivered",
    subject: "Important information about your treatment plan",
    body: "Dear Sarah,\n\nDr. Anderson wanted to share some additional information about your treatment plan that may help with your decision.\n\nYou can review your full plan details here:\nhttps://followdent.com/portal/t/bcd890\n\nWe offer financing options through CareCredit to help make treatment affordable. We'd love to answer any questions you have.\n\nWarm regards,\nRiverside Family Dental",
    external_id: "sandbox-email-ext-004",
    error: null,
    sent_at: daysAgo(3),
    delivered_at: daysAgo(3),
    read_at: daysAgo(3),
    created_at: daysAgo(3),
  },
  // Inbound reply from Sarah
  {
    id: "sandbox-message-015",
    practice_id: "sandbox-practice-001",
    patient_id: "sandbox-patient-005",
    enrollment_id: "sandbox-enrollment-005",
    touchpoint_id: null,
    channel: "sms",
    direction: "inbound",
    status: "received",
    subject: null,
    body: "I already scheduled this with you guys last week",
    external_id: "sandbox-sms-ext-011",
    error: null,
    sent_at: null,
    delivered_at: null,
    read_at: null,
    created_at: daysAgo(3),
  },

  // --- Outbound messages for patient 006 (Carlos Mendoza) — Crown sequence ---
  {
    id: "sandbox-message-016",
    practice_id: "sandbox-practice-001",
    patient_id: "sandbox-patient-006",
    enrollment_id: "sandbox-enrollment-006",
    touchpoint_id: "sandbox-touchpoint-001",
    channel: "sms",
    direction: "outbound",
    status: "delivered",
    subject: null,
    body: "Hi Carlos, this is Riverside Family Dental. You have a treatment plan ready to schedule. View details and book here: https://followdent.com/portal/t/efg123",
    external_id: "sandbox-sms-ext-012",
    error: null,
    sent_at: daysAgo(13),
    delivered_at: daysAgo(13),
    read_at: null,
    created_at: daysAgo(13),
  },
  {
    id: "sandbox-message-017",
    practice_id: "sandbox-practice-001",
    patient_id: "sandbox-patient-006",
    enrollment_id: "sandbox-enrollment-006",
    touchpoint_id: "sandbox-touchpoint-002",
    channel: "email",
    direction: "outbound",
    status: "delivered",
    subject: "Your treatment plan at Riverside Family Dental",
    body: "Dear Carlos,\n\nDr. Anderson wanted to follow up on the treatment plan we discussed during your last visit. Completing this treatment is important for your long-term oral health.\n\nYou can view your plan details and schedule here:\nhttps://followdent.com/portal/t/hij456\n\nWe have several openings this month and can work with your schedule.\n\nBest regards,\nRiverside Family Dental",
    external_id: "sandbox-email-ext-005",
    error: null,
    sent_at: daysAgo(6),
    delivered_at: daysAgo(6),
    read_at: null,
    created_at: daysAgo(6),
  },

  // --- Outbound messages for patient 007 (Emily Thornton) — Crown sequence ---
  {
    id: "sandbox-message-018",
    practice_id: "sandbox-practice-001",
    patient_id: "sandbox-patient-007",
    enrollment_id: "sandbox-enrollment-007",
    touchpoint_id: "sandbox-touchpoint-001",
    channel: "sms",
    direction: "outbound",
    status: "delivered",
    subject: null,
    body: "Hi Emily, this is Riverside Family Dental. You have a treatment plan ready to schedule. View details and book here: https://followdent.com/portal/t/klm789",
    external_id: "sandbox-sms-ext-013",
    error: null,
    sent_at: daysAgo(4),
    delivered_at: daysAgo(4),
    read_at: null,
    created_at: daysAgo(4),
  },

  // --- Outbound messages for patient 008 (Robert Chen) — Perio sequence ---
  {
    id: "sandbox-message-019",
    practice_id: "sandbox-practice-001",
    patient_id: "sandbox-patient-008",
    enrollment_id: "sandbox-enrollment-008",
    touchpoint_id: "sandbox-touchpoint-008",
    channel: "sms",
    direction: "outbound",
    status: "delivered",
    subject: null,
    body: "Hi Robert, Riverside Family Dental here. We wanted to check in about the treatment plan from your recent visit. View your plan and schedule here: https://followdent.com/portal/t/nop012",
    external_id: "sandbox-sms-ext-014",
    error: null,
    sent_at: daysAgo(9),
    delivered_at: daysAgo(9),
    read_at: null,
    created_at: daysAgo(9),
  },

  // --- Success story messages (patients 013-015) ---
  {
    id: "sandbox-message-020",
    practice_id: "sandbox-practice-001",
    patient_id: "sandbox-patient-013",
    enrollment_id: "sandbox-enrollment-009",
    touchpoint_id: "sandbox-touchpoint-001",
    channel: "sms",
    direction: "outbound",
    status: "delivered",
    subject: null,
    body: "Hi Jennifer, this is Riverside Family Dental. You have a treatment plan ready to schedule. View details and book here: https://followdent.com/portal/t/qrs345",
    external_id: "sandbox-sms-ext-015",
    error: null,
    sent_at: daysAgo(27),
    delivered_at: daysAgo(27),
    read_at: null,
    created_at: daysAgo(27),
  },
  {
    id: "sandbox-message-021",
    practice_id: "sandbox-practice-001",
    patient_id: "sandbox-patient-013",
    enrollment_id: "sandbox-enrollment-009",
    touchpoint_id: "sandbox-touchpoint-002",
    channel: "email",
    direction: "outbound",
    status: "delivered",
    subject: "Your treatment plan at Riverside Family Dental",
    body: "Dear Jennifer,\n\nDr. Anderson wanted to follow up on the treatment plan we discussed during your last visit.\n\nYou can view your plan details and schedule here:\nhttps://followdent.com/portal/t/tuv678\n\nOr reply to this email or call us at (720) 555-0142 to book.\n\nBest regards,\nRiverside Family Dental",
    external_id: "sandbox-email-ext-006",
    error: null,
    sent_at: daysAgo(20),
    delivered_at: daysAgo(20),
    read_at: daysAgo(19),
    created_at: daysAgo(20),
  },
  {
    id: "sandbox-message-022",
    practice_id: "sandbox-practice-001",
    patient_id: "sandbox-patient-013",
    enrollment_id: "sandbox-enrollment-009",
    touchpoint_id: null,
    channel: "sms",
    direction: "inbound",
    status: "received",
    subject: null,
    body: "Yes I'd like to schedule, can I come in next Tuesday?",
    external_id: "sandbox-sms-ext-016",
    error: null,
    sent_at: null,
    delivered_at: null,
    read_at: daysAgo(8),
    created_at: daysAgo(9),
  },

  {
    id: "sandbox-message-023",
    practice_id: "sandbox-practice-001",
    patient_id: "sandbox-patient-014",
    enrollment_id: "sandbox-enrollment-010",
    touchpoint_id: "sandbox-touchpoint-004",
    channel: "sms",
    direction: "outbound",
    status: "delivered",
    subject: null,
    body: "Hi Michael! This is Riverside Family Dental. Just following up on your treatment plan. View your plan details here: https://followdent.com/portal/t/wxy901 — happy to answer any questions.",
    external_id: "sandbox-sms-ext-017",
    error: null,
    sent_at: daysAgo(33),
    delivered_at: daysAgo(33),
    read_at: null,
    created_at: daysAgo(33),
  },
  {
    id: "sandbox-message-024",
    practice_id: "sandbox-practice-001",
    patient_id: "sandbox-patient-014",
    enrollment_id: "sandbox-enrollment-010",
    touchpoint_id: "sandbox-touchpoint-005",
    channel: "email",
    direction: "outbound",
    status: "delivered",
    subject: "Important information about your treatment plan",
    body: "Dear Michael,\n\nDr. Anderson wanted to share some additional information about your treatment plan.\n\nYou can review your full plan details here:\nhttps://followdent.com/portal/t/zab234\n\nWe offer financing options through CareCredit to help make treatment affordable.\n\nWarm regards,\nRiverside Family Dental",
    external_id: "sandbox-email-ext-007",
    error: null,
    sent_at: daysAgo(28),
    delivered_at: daysAgo(28),
    read_at: daysAgo(27),
    created_at: daysAgo(28),
  },
  {
    id: "sandbox-message-025",
    practice_id: "sandbox-practice-001",
    patient_id: "sandbox-patient-014",
    enrollment_id: "sandbox-enrollment-010",
    touchpoint_id: "sandbox-touchpoint-006",
    channel: "sms",
    direction: "outbound",
    status: "delivered",
    subject: null,
    body: "Michael, quick reminder from Riverside Family Dental — you have a treatment plan ready to schedule. We have limited openings this month. View your plan: https://followdent.com/portal/t/cde567 — Reply YES to reserve a spot.",
    external_id: "sandbox-sms-ext-018",
    error: null,
    sent_at: daysAgo(21),
    delivered_at: daysAgo(21),
    read_at: null,
    created_at: daysAgo(21),
  },
  {
    id: "sandbox-message-026",
    practice_id: "sandbox-practice-001",
    patient_id: "sandbox-patient-014",
    enrollment_id: "sandbox-enrollment-010",
    touchpoint_id: null,
    channel: "sms",
    direction: "inbound",
    status: "received",
    subject: null,
    body: "YES please book me in. Mornings work best.",
    external_id: "sandbox-sms-ext-019",
    error: null,
    sent_at: null,
    delivered_at: null,
    read_at: daysAgo(12),
    created_at: daysAgo(13),
  },

  {
    id: "sandbox-message-027",
    practice_id: "sandbox-practice-001",
    patient_id: "sandbox-patient-015",
    enrollment_id: "sandbox-enrollment-011",
    touchpoint_id: "sandbox-touchpoint-008",
    channel: "sms",
    direction: "outbound",
    status: "delivered",
    subject: null,
    body: "Hi Amara, Riverside Family Dental here. We wanted to check in about the treatment plan from your recent visit. View your plan and schedule here: https://followdent.com/portal/t/fgh890",
    external_id: "sandbox-sms-ext-020",
    error: null,
    sent_at: daysAgo(15),
    delivered_at: daysAgo(15),
    read_at: null,
    created_at: daysAgo(15),
  },
  {
    id: "sandbox-message-028",
    practice_id: "sandbox-practice-001",
    patient_id: "sandbox-patient-015",
    enrollment_id: "sandbox-enrollment-011",
    touchpoint_id: null,
    channel: "sms",
    direction: "inbound",
    status: "received",
    subject: null,
    body: "Hi! Yes I've been meaning to call. Can I come in Friday?",
    external_id: "sandbox-sms-ext-021",
    error: null,
    sent_at: null,
    delivered_at: null,
    read_at: daysAgo(5),
    created_at: daysAgo(7),
  },

  // --- Additional outbound messages to fill out the 40+ count ---
  // Failed delivery
  {
    id: "sandbox-message-029",
    practice_id: "sandbox-practice-001",
    patient_id: "sandbox-patient-006",
    enrollment_id: "sandbox-enrollment-006",
    touchpoint_id: "sandbox-touchpoint-001",
    channel: "sms",
    direction: "outbound",
    status: "failed",
    subject: null,
    body: "Hi Carlos, this is Riverside Family Dental. You have a treatment plan ready to schedule...",
    external_id: "sandbox-sms-ext-022",
    error: "Carrier rejected: unreachable number",
    sent_at: daysAgo(14),
    delivered_at: null,
    read_at: null,
    created_at: daysAgo(14),
  },

  // Voicemail messages
  {
    id: "sandbox-message-030",
    practice_id: "sandbox-practice-001",
    patient_id: "sandbox-patient-013",
    enrollment_id: "sandbox-enrollment-009",
    touchpoint_id: "sandbox-touchpoint-003",
    channel: "voicemail",
    direction: "outbound",
    status: "delivered",
    subject: null,
    body: "Hi Jennifer, this is a friendly reminder from Riverside Family Dental about your treatment plan. We want to make sure you get the care you need. Check your text or email for a secure link to view your plan, or give us a call at (720) 555-0142. Have a great day!",
    external_id: "sandbox-vm-ext-001",
    error: null,
    sent_at: daysAgo(9),
    delivered_at: daysAgo(9),
    read_at: null,
    created_at: daysAgo(9),
  },
  {
    id: "sandbox-message-031",
    practice_id: "sandbox-practice-001",
    patient_id: "sandbox-patient-014",
    enrollment_id: "sandbox-enrollment-010",
    touchpoint_id: "sandbox-touchpoint-007",
    channel: "voicemail",
    direction: "outbound",
    status: "delivered",
    subject: null,
    body: "Hi Michael, this is Riverside Family Dental reaching out one more time about your treatment plan. We care about your health and want to make sure you have everything you need. Check your text or email for a secure link to view your plan, or call us at (720) 555-0142. Take care!",
    external_id: "sandbox-vm-ext-002",
    error: null,
    sent_at: daysAgo(5),
    delivered_at: daysAgo(5),
    read_at: null,
    created_at: daysAgo(5),
  },

  // More outbound to pad the count — sent/delivered statuses
  {
    id: "sandbox-message-032",
    practice_id: "sandbox-practice-001",
    patient_id: "sandbox-patient-004",
    enrollment_id: "sandbox-enrollment-004",
    touchpoint_id: "sandbox-touchpoint-008",
    channel: "sms",
    direction: "outbound",
    status: "sent",
    subject: null,
    body: "Hi David, Riverside Family Dental here. Just a quick follow-up about your treatment plan. View details here: https://followdent.com/portal/t/ijk345",
    external_id: "sandbox-sms-ext-023",
    error: null,
    sent_at: daysAgo(18),
    delivered_at: null,
    read_at: null,
    created_at: daysAgo(18),
  },
  {
    id: "sandbox-message-033",
    practice_id: "sandbox-practice-001",
    patient_id: "sandbox-patient-008",
    enrollment_id: "sandbox-enrollment-008",
    touchpoint_id: "sandbox-touchpoint-009",
    channel: "email",
    direction: "outbound",
    status: "delivered",
    subject: "Follow-up: Your recommended treatment",
    body: "Dear Robert,\n\nWe're reaching out about the treatment plan from your last visit.\n\nYou can view your plan details and schedule here:\nhttps://followdent.com/portal/t/lmn678\n\nOr reply to this email or call (720) 555-0142 to schedule.\n\nThank you,\nRiverside Family Dental",
    external_id: "sandbox-email-ext-008",
    error: null,
    sent_at: daysAgo(2),
    delivered_at: daysAgo(2),
    read_at: null,
    created_at: daysAgo(2),
  },
  {
    id: "sandbox-message-034",
    practice_id: "sandbox-practice-001",
    patient_id: "sandbox-patient-005",
    enrollment_id: "sandbox-enrollment-005",
    touchpoint_id: "sandbox-touchpoint-004",
    channel: "sms",
    direction: "outbound",
    status: "delivered",
    subject: null,
    body: "Hi Sarah! Riverside Family Dental here — just checking in about your treatment plan. View details here: https://followdent.com/portal/t/opq901 Let us know if you have any questions!",
    external_id: "sandbox-sms-ext-024",
    error: null,
    sent_at: daysAgo(9),
    delivered_at: daysAgo(9),
    read_at: null,
    created_at: daysAgo(9),
  },
  {
    id: "sandbox-message-035",
    practice_id: "sandbox-practice-001",
    patient_id: "sandbox-patient-007",
    enrollment_id: "sandbox-enrollment-007",
    touchpoint_id: "sandbox-touchpoint-001",
    channel: "sms",
    direction: "outbound",
    status: "delivered",
    subject: null,
    body: "Hi Emily, this is Riverside Family Dental. Following up on your treatment plan — we have openings this week. View your plan here: https://followdent.com/portal/t/rst234",
    external_id: "sandbox-sms-ext-025",
    error: null,
    sent_at: daysAgo(3),
    delivered_at: daysAgo(3),
    read_at: null,
    created_at: daysAgo(3),
  },
  {
    id: "sandbox-message-036",
    practice_id: "sandbox-practice-001",
    patient_id: "sandbox-patient-001",
    enrollment_id: "sandbox-enrollment-001",
    touchpoint_id: "sandbox-touchpoint-001",
    channel: "sms",
    direction: "outbound",
    status: "delivered",
    subject: null,
    body: "Maria, just following up — we'd love to get your treatment plan scheduled before the end of the month. View your plan: https://followdent.com/portal/t/uvw567",
    external_id: "sandbox-sms-ext-026",
    error: null,
    sent_at: daysAgo(15),
    delivered_at: daysAgo(15),
    read_at: null,
    created_at: daysAgo(15),
  },
  {
    id: "sandbox-message-037",
    practice_id: "sandbox-practice-001",
    patient_id: "sandbox-patient-003",
    enrollment_id: "sandbox-enrollment-003",
    touchpoint_id: "sandbox-touchpoint-001",
    channel: "sms",
    direction: "outbound",
    status: "delivered",
    subject: null,
    body: "Hi Priya, Riverside Family Dental here! Quick follow-up about your treatment plan — we can usually fit you in the same week. View your plan here: https://followdent.com/portal/t/xyz890",
    external_id: "sandbox-sms-ext-027",
    error: null,
    sent_at: daysAgo(6),
    delivered_at: daysAgo(6),
    read_at: null,
    created_at: daysAgo(6),
  },
  // Another failed message
  {
    id: "sandbox-message-038",
    practice_id: "sandbox-practice-001",
    patient_id: "sandbox-patient-008",
    enrollment_id: "sandbox-enrollment-008",
    touchpoint_id: "sandbox-touchpoint-008",
    channel: "sms",
    direction: "outbound",
    status: "failed",
    subject: null,
    body: "Hi Robert, Riverside Family Dental here. You have a treatment plan ready to schedule...",
    external_id: "sandbox-sms-ext-028",
    error: "Message body too long for SMS",
    sent_at: daysAgo(15),
    delivered_at: null,
    read_at: null,
    created_at: daysAgo(15),
  },
  // Queued messages
  {
    id: "sandbox-message-039",
    practice_id: "sandbox-practice-001",
    patient_id: "sandbox-patient-006",
    enrollment_id: "sandbox-enrollment-006",
    touchpoint_id: "sandbox-touchpoint-003",
    channel: "voicemail",
    direction: "outbound",
    status: "queued",
    subject: null,
    body: "Hi Carlos, this is a friendly reminder from Riverside Family Dental about your treatment plan...",
    external_id: null,
    error: null,
    sent_at: null,
    delivered_at: null,
    read_at: null,
    created_at: hoursAgo(2),
  },
  {
    id: "sandbox-message-040",
    practice_id: "sandbox-practice-001",
    patient_id: "sandbox-patient-002",
    enrollment_id: "sandbox-enrollment-002",
    touchpoint_id: "sandbox-touchpoint-007",
    channel: "voicemail",
    direction: "outbound",
    status: "queued",
    subject: null,
    body: "Hi James, this is Riverside Family Dental reaching out one more time about your treatment plan...",
    external_id: null,
    error: null,
    sent_at: null,
    delivered_at: null,
    read_at: null,
    created_at: hoursAgo(1),
  },
  {
    id: "sandbox-message-041",
    practice_id: "sandbox-practice-001",
    patient_id: "sandbox-patient-007",
    enrollment_id: "sandbox-enrollment-007",
    touchpoint_id: "sandbox-touchpoint-002",
    channel: "email",
    direction: "outbound",
    status: "queued",
    subject: "Your treatment plan at Riverside Family Dental",
    body: "Dear Emily,\n\nDr. Anderson wanted to follow up on your treatment plan. View details here: https://followdent.com/portal/t/abc901...",
    external_id: null,
    error: null,
    sent_at: null,
    delivered_at: null,
    read_at: null,
    created_at: hoursAgo(3),
  },
];

// ─── Conversations (for Inbox) ────────────────────────────────────────────────

export const SANDBOX_CONVERSATIONS: Conversation[] = [
  {
    id: "sandbox-conversation-001",
    practice_id: "sandbox-practice-001",
    patient_id: "sandbox-patient-001",
    last_message_at: daysAgo(2),
    last_message_preview: "Hi yes I would like to schedule, what times do you have?",
    unread_count: 1,
    status: "open",
    assigned_to: null,
    created_at: daysAgo(12),
    updated_at: daysAgo(2),
  },
  {
    id: "sandbox-conversation-002",
    practice_id: "sandbox-practice-001",
    patient_id: "sandbox-patient-002",
    last_message_at: daysAgo(5),
    last_message_preview: "Can you call me instead? I prefer to talk on the phone.",
    unread_count: 1,
    status: "open",
    assigned_to: null,
    created_at: daysAgo(18),
    updated_at: daysAgo(5),
  },
  {
    id: "sandbox-conversation-003",
    practice_id: "sandbox-practice-001",
    patient_id: "sandbox-patient-003",
    last_message_at: daysAgo(1),
    last_message_preview: "Yes! Book me in please \u{1F642}",
    unread_count: 1,
    status: "open",
    assigned_to: null,
    created_at: daysAgo(5),
    updated_at: daysAgo(1),
  },
  {
    id: "sandbox-conversation-004",
    practice_id: "sandbox-practice-001",
    patient_id: "sandbox-patient-004",
    last_message_at: daysAgo(8),
    last_message_preview: "Not right now, maybe next month",
    unread_count: 0,
    status: "open",
    assigned_to: null,
    created_at: daysAgo(17),
    updated_at: daysAgo(8),
  },
  {
    id: "sandbox-conversation-005",
    practice_id: "sandbox-practice-001",
    patient_id: "sandbox-patient-005",
    last_message_at: daysAgo(3),
    last_message_preview: "I already scheduled this with you guys last week",
    unread_count: 1,
    status: "open",
    assigned_to: null,
    created_at: daysAgo(8),
    updated_at: daysAgo(3),
  },
  {
    id: "sandbox-conversation-006",
    practice_id: "sandbox-practice-001",
    patient_id: "sandbox-patient-013",
    last_message_at: daysAgo(8),
    last_message_preview: "Yes I'd like to schedule, can I come in next Tuesday?",
    unread_count: 0,
    status: "closed",
    assigned_to: null,
    created_at: daysAgo(27),
    updated_at: daysAgo(8),
  },
  {
    id: "sandbox-conversation-007",
    practice_id: "sandbox-practice-001",
    patient_id: "sandbox-patient-014",
    last_message_at: daysAgo(12),
    last_message_preview: "YES please book me in. Mornings work best.",
    unread_count: 0,
    status: "closed",
    assigned_to: null,
    created_at: daysAgo(33),
    updated_at: daysAgo(12),
  },
  {
    id: "sandbox-conversation-008",
    practice_id: "sandbox-practice-001",
    patient_id: "sandbox-patient-015",
    last_message_at: daysAgo(5),
    last_message_preview: "Hi! Yes I've been meaning to call. Can I come in Friday?",
    unread_count: 0,
    status: "closed",
    assigned_to: null,
    created_at: daysAgo(15),
    updated_at: daysAgo(5),
  },
];

// ─── Analytics seed data ──────────────────────────────────────────────────────

export const SANDBOX_DAILY_REVENUE = generateDailyRevenue(90);

export const SANDBOX_DASHBOARD_STATS: DashboardStats = {
  revenue_recovered: 28450,
  revenue_change: 18.3,
  active_patients: 15,
  patients_change: 12.5,
  plans_in_sequence: 8,
  messages_sent: 53,
  delivery_rate: 94.3,
  conversion_rate: 37.5,
  conversion_change: 5.2,
};

export const SANDBOX_ANALYTICS_STATS: AnalyticsStats = {
  revenue_recovered: 28450,
  best_sequence: { name: "High-Value Implant & Prosthetic", conversion_rate: 45.4 },
  best_channel: { channel: "sms", conversion_rate: 42.1 },
  avg_days_to_book: 11.3,
};

export const SANDBOX_CHANNEL_BREAKDOWN: ChannelBreakdownItem[] = [
  { channel: "sms", count: 31 },
  { channel: "email", count: 15 },
  { channel: "voicemail", count: 7 },
];

export const SANDBOX_SEQUENCE_CONVERSIONS: SequenceConversionRow[] = [
  {
    id: "sandbox-sequence-001",
    name: "Standard Crown & Restorative",
    sent: 24,
    delivered: 22,
    replied: 9,
    booked: 9,
    conversion_rate: 37.5,
  },
  {
    id: "sandbox-sequence-002",
    name: "High-Value Implant & Prosthetic",
    sent: 11,
    delivered: 10,
    replied: 7,
    booked: 5,
    conversion_rate: 45.4,
  },
  {
    id: "sandbox-sequence-003",
    name: "Perio & Preventive Follow-Up",
    sent: 18,
    delivered: 17,
    replied: 6,
    booked: 4,
    conversion_rate: 22.2,
  },
];

export const SANDBOX_FUNNEL: FunnelStageItem[] = [
  { stage: "Detected", value: 53 },
  { stage: "In Sequence", value: 38 },
  { stage: "Replied", value: 19 },
  { stage: "Booked", value: 14 },
];

export const SANDBOX_RECENT_ACTIVITY: ActivityItem[] = [
  {
    id: "sandbox-activity-001",
    patient_name: "Maria Castellano",
    action: "Replied to SMS — wants to schedule crown",
    timestamp: daysAgo(2),
    type: "success",
  },
  {
    id: "sandbox-activity-002",
    patient_name: "Priya Nair",
    action: "Replied to SMS — ready to book composite",
    timestamp: daysAgo(1),
    type: "success",
  },
  {
    id: "sandbox-activity-003",
    patient_name: "James Whitfield",
    action: "Replied — prefers phone call",
    timestamp: daysAgo(5),
    type: "info",
  },
  {
    id: "sandbox-activity-004",
    patient_name: "Emily Thornton",
    action: "SMS delivered — root canal follow-up",
    timestamp: daysAgo(4),
    type: "info",
  },
  {
    id: "sandbox-activity-005",
    patient_name: "David Kowalski",
    action: "Replied — not ready yet, maybe next month",
    timestamp: daysAgo(8),
    type: "warning",
  },
  {
    id: "sandbox-activity-006",
    patient_name: "Sarah Okonkwo",
    action: "Replied — already scheduled",
    timestamp: daysAgo(3),
    type: "info",
  },
  {
    id: "sandbox-activity-007",
    patient_name: "Jennifer Hawkins",
    action: "Booked crown appointment — $1,450 recovered",
    timestamp: daysAgo(8),
    type: "success",
  },
  {
    id: "sandbox-activity-008",
    patient_name: "Michael Torres",
    action: "Booked implant crown — $3,800 recovered",
    timestamp: daysAgo(12),
    type: "success",
  },
  {
    id: "sandbox-activity-009",
    patient_name: "Amara Diallo",
    action: "Booked extraction — $650 recovered",
    timestamp: daysAgo(6),
    type: "success",
  },
  {
    id: "sandbox-activity-010",
    patient_name: "Carlos Mendoza",
    action: "SMS delivery failed — carrier rejected",
    timestamp: daysAgo(14),
    type: "warning",
  },
];

// ─── Utility: check if an ID is a sandbox record ─────────────────────────────

export function isSandboxId(id: string): boolean {
  return id.startsWith("sandbox-");
}
