// ADA CDT Dental Procedure Codes Reference
// Based on CDT-2024 / CDT-2025 code set

export interface DentalCode {
  code: string;
  label: string;
  category: string;
}

export interface DentalCodeCategory {
  name: string;
  range: string;
  codes: DentalCode[];
}

const diagnosticCodes: DentalCode[] = [
  { code: 'D0120', label: 'Periodic oral evaluation', category: 'Diagnostic' },
  { code: 'D0140', label: 'Limited oral evaluation', category: 'Diagnostic' },
  { code: 'D0145', label: 'Oral evaluation — patient under 3', category: 'Diagnostic' },
  { code: 'D0150', label: 'Comprehensive oral evaluation', category: 'Diagnostic' },
  { code: 'D0160', label: 'Detailed/extensive oral evaluation', category: 'Diagnostic' },
  { code: 'D0170', label: 'Re-evaluation — limited, problem-focused', category: 'Diagnostic' },
  { code: 'D0171', label: 'Re-evaluation post-operative', category: 'Diagnostic' },
  { code: 'D0180', label: 'Comprehensive periodontal evaluation', category: 'Diagnostic' },
  { code: 'D0190', label: 'Screening', category: 'Diagnostic' },
  { code: 'D0191', label: 'Assessment of a patient', category: 'Diagnostic' },
  { code: 'D0210', label: 'Complete series of radiographic images', category: 'Diagnostic' },
  { code: 'D0220', label: 'Periapical radiographic image — first', category: 'Diagnostic' },
  { code: 'D0230', label: 'Periapical radiographic image — each additional', category: 'Diagnostic' },
  { code: 'D0240', label: 'Occlusal radiographic image', category: 'Diagnostic' },
  { code: 'D0250', label: 'Extra-oral 2D radiographic image', category: 'Diagnostic' },
  { code: 'D0251', label: 'Extra-oral posterior dental radiographic image', category: 'Diagnostic' },
  { code: 'D0270', label: 'Bitewing — single image', category: 'Diagnostic' },
  { code: 'D0272', label: 'Bitewings — two images', category: 'Diagnostic' },
  { code: 'D0273', label: 'Bitewings — three images', category: 'Diagnostic' },
  { code: 'D0274', label: 'Bitewings — four images', category: 'Diagnostic' },
  { code: 'D0277', label: 'Vertical bitewings — 7 to 8 images', category: 'Diagnostic' },
  { code: 'D0330', label: 'Panoramic radiographic image', category: 'Diagnostic' },
  { code: 'D0340', label: '2D cephalometric radiographic image', category: 'Diagnostic' },
  { code: 'D0350', label: '2D oral/facial photographic image', category: 'Diagnostic' },
  { code: 'D0364', label: 'Cone beam CT — limited field', category: 'Diagnostic' },
  { code: 'D0365', label: 'Cone beam CT — one full arch', category: 'Diagnostic' },
  { code: 'D0366', label: 'Cone beam CT — two full arches', category: 'Diagnostic' },
  { code: 'D0371', label: 'Cone beam CT — TMJ', category: 'Diagnostic' },
  { code: 'D0380', label: 'Cone beam CT — for sleep apnea', category: 'Diagnostic' },
  { code: 'D0460', label: 'Pulp vitality tests', category: 'Diagnostic' },
  { code: 'D0470', label: 'Diagnostic casts', category: 'Diagnostic' },
  { code: 'D0480', label: 'Accession of tissue — gross exam', category: 'Diagnostic' },
  { code: 'D0485', label: 'Accession of tissue — comprehensive', category: 'Diagnostic' },
  { code: 'D0600', label: 'Non-ionizing diagnostic procedure', category: 'Diagnostic' },
  { code: 'D0601', label: 'Caries risk assessment — low', category: 'Diagnostic' },
  { code: 'D0602', label: 'Caries risk assessment — moderate', category: 'Diagnostic' },
  { code: 'D0603', label: 'Caries risk assessment — high', category: 'Diagnostic' },
  { code: 'D0701', label: 'Panoramic radiographic image — 3D', category: 'Diagnostic' },
  { code: 'D0702', label: '2-3 teeth periapical radiographic image — 3D', category: 'Diagnostic' },
  { code: 'D0703', label: 'Crown radiographic image — 3D', category: 'Diagnostic' },
  { code: 'D0704', label: 'Implant radiographic image — 3D', category: 'Diagnostic' },
  { code: 'D0705', label: 'Periapical radiographic image — 3D', category: 'Diagnostic' },
  { code: 'D0706', label: 'Posterior radiographic image — 3D', category: 'Diagnostic' },
  { code: 'D0707', label: 'Periapical radiographic image — 3D, edentulous', category: 'Diagnostic' },
  { code: 'D0708', label: 'Dental implant radiographic image — 3D', category: 'Diagnostic' },
  { code: 'D0709', label: 'Cone beam CT — single tooth', category: 'Diagnostic' },
];

const preventiveCodes: DentalCode[] = [
  { code: 'D1110', label: 'Prophylaxis — adult', category: 'Preventive' },
  { code: 'D1120', label: 'Prophylaxis — child', category: 'Preventive' },
  { code: 'D1206', label: 'Topical fluoride — varnish', category: 'Preventive' },
  { code: 'D1208', label: 'Topical fluoride — excluding varnish', category: 'Preventive' },
  { code: 'D1310', label: 'Nutritional counseling', category: 'Preventive' },
  { code: 'D1320', label: 'Tobacco counseling', category: 'Preventive' },
  { code: 'D1321', label: 'Counseling for high-risk substance use', category: 'Preventive' },
  { code: 'D1330', label: 'Oral hygiene instructions', category: 'Preventive' },
  { code: 'D1351', label: 'Sealant — per tooth', category: 'Preventive' },
  { code: 'D1352', label: 'Preventive resin restoration', category: 'Preventive' },
  { code: 'D1353', label: 'Sealant repair — per tooth', category: 'Preventive' },
  { code: 'D1354', label: 'Interim caries-arresting medicament', category: 'Preventive' },
  { code: 'D1355', label: 'Caries preventive medicament application — per tooth', category: 'Preventive' },
  { code: 'D1510', label: 'Space maintainer — fixed, unilateral', category: 'Preventive' },
  { code: 'D1516', label: 'Space maintainer — fixed, bilateral — maxillary', category: 'Preventive' },
  { code: 'D1517', label: 'Space maintainer — fixed, bilateral — mandibular', category: 'Preventive' },
  { code: 'D1520', label: 'Space maintainer — removable, unilateral', category: 'Preventive' },
  { code: 'D1526', label: 'Space maintainer — removable, bilateral — maxillary', category: 'Preventive' },
  { code: 'D1527', label: 'Space maintainer — removable, bilateral — mandibular', category: 'Preventive' },
  { code: 'D1551', label: 'Re-cement or re-bond bilateral space maintainer — maxillary', category: 'Preventive' },
  { code: 'D1552', label: 'Re-cement or re-bond bilateral space maintainer — mandibular', category: 'Preventive' },
  { code: 'D1553', label: 'Re-cement or re-bond unilateral space maintainer — per quadrant', category: 'Preventive' },
  { code: 'D1556', label: 'Removal of fixed unilateral space maintainer — per quadrant', category: 'Preventive' },
  { code: 'D1557', label: 'Removal of fixed bilateral space maintainer — maxillary', category: 'Preventive' },
  { code: 'D1558', label: 'Removal of fixed bilateral space maintainer — mandibular', category: 'Preventive' },
  { code: 'D1575', label: 'Distal shoe space maintainer — fixed, unilateral', category: 'Preventive' },
];

const restorativeCodes: DentalCode[] = [
  { code: 'D2140', label: 'Amalgam — one surface, primary or permanent', category: 'Restorative' },
  { code: 'D2150', label: 'Amalgam — two surfaces, primary or permanent', category: 'Restorative' },
  { code: 'D2160', label: 'Amalgam — three surfaces, primary or permanent', category: 'Restorative' },
  { code: 'D2161', label: 'Amalgam — four or more surfaces, primary or permanent', category: 'Restorative' },
  { code: 'D2330', label: 'Resin-based composite — one surface, anterior', category: 'Restorative' },
  { code: 'D2331', label: 'Resin-based composite — two surfaces, anterior', category: 'Restorative' },
  { code: 'D2332', label: 'Resin-based composite — three surfaces, anterior', category: 'Restorative' },
  { code: 'D2335', label: 'Resin-based composite — four or more surfaces, anterior', category: 'Restorative' },
  { code: 'D2390', label: 'Resin-based composite crown — anterior', category: 'Restorative' },
  { code: 'D2391', label: 'Resin-based composite — one surface, posterior, primary', category: 'Restorative' },
  { code: 'D2392', label: 'Resin-based composite — two surfaces, posterior', category: 'Restorative' },
  { code: 'D2393', label: 'Resin-based composite — three surfaces, posterior', category: 'Restorative' },
  { code: 'D2394', label: 'Resin-based composite — four or more surfaces, posterior', category: 'Restorative' },
  { code: 'D2510', label: 'Inlay — metallic — one surface', category: 'Restorative' },
  { code: 'D2520', label: 'Inlay — metallic — two surfaces', category: 'Restorative' },
  { code: 'D2530', label: 'Inlay — metallic — three or more surfaces', category: 'Restorative' },
  { code: 'D2542', label: 'Onlay — metallic — two surfaces', category: 'Restorative' },
  { code: 'D2543', label: 'Onlay — metallic — three surfaces', category: 'Restorative' },
  { code: 'D2544', label: 'Onlay — metallic — four or more surfaces', category: 'Restorative' },
  { code: 'D2610', label: 'Inlay — porcelain/ceramic — one surface', category: 'Restorative' },
  { code: 'D2620', label: 'Inlay — porcelain/ceramic — two surfaces', category: 'Restorative' },
  { code: 'D2630', label: 'Inlay — porcelain/ceramic — three or more surfaces', category: 'Restorative' },
  { code: 'D2642', label: 'Onlay — porcelain/ceramic — two surfaces', category: 'Restorative' },
  { code: 'D2643', label: 'Onlay — porcelain/ceramic — three surfaces', category: 'Restorative' },
  { code: 'D2644', label: 'Onlay — porcelain/ceramic — four or more surfaces', category: 'Restorative' },
  { code: 'D2650', label: 'Inlay — resin-based composite — one surface', category: 'Restorative' },
  { code: 'D2651', label: 'Inlay — resin-based composite — two surfaces', category: 'Restorative' },
  { code: 'D2652', label: 'Inlay — resin-based composite — three or more surfaces', category: 'Restorative' },
  { code: 'D2662', label: 'Onlay — resin-based composite — two surfaces', category: 'Restorative' },
  { code: 'D2663', label: 'Onlay — resin-based composite — three surfaces', category: 'Restorative' },
  { code: 'D2664', label: 'Onlay — resin-based composite — four or more surfaces', category: 'Restorative' },
  { code: 'D2710', label: 'Crown — resin-based composite (indirect)', category: 'Restorative' },
  { code: 'D2712', label: 'Crown — 3/4 resin-based composite (indirect)', category: 'Restorative' },
  { code: 'D2720', label: 'Crown — resin with high noble metal', category: 'Restorative' },
  { code: 'D2721', label: 'Crown — resin with predominantly base metal', category: 'Restorative' },
  { code: 'D2722', label: 'Crown — resin with noble metal', category: 'Restorative' },
  { code: 'D2740', label: 'Crown — porcelain/ceramic substrate', category: 'Restorative' },
  { code: 'D2750', label: 'Crown — porcelain fused to high noble metal', category: 'Restorative' },
  { code: 'D2751', label: 'Crown — porcelain fused to predominantly base metal', category: 'Restorative' },
  { code: 'D2752', label: 'Crown — porcelain fused to noble metal', category: 'Restorative' },
  { code: 'D2753', label: 'Crown — porcelain fused to titanium and titanium alloys', category: 'Restorative' },
  { code: 'D2780', label: 'Crown — 3/4 cast high noble metal', category: 'Restorative' },
  { code: 'D2781', label: 'Crown — 3/4 cast predominantly base metal', category: 'Restorative' },
  { code: 'D2782', label: 'Crown — 3/4 cast noble metal', category: 'Restorative' },
  { code: 'D2783', label: 'Crown — 3/4 porcelain/ceramic', category: 'Restorative' },
  { code: 'D2790', label: 'Crown — full cast high noble metal', category: 'Restorative' },
  { code: 'D2791', label: 'Crown — full cast predominantly base metal', category: 'Restorative' },
  { code: 'D2792', label: 'Crown — full cast noble metal', category: 'Restorative' },
  { code: 'D2794', label: 'Crown — titanium and titanium alloys', category: 'Restorative' },
  { code: 'D2799', label: 'Provisional crown', category: 'Restorative' },
  { code: 'D2910', label: 'Re-cement or re-bond inlay, onlay, veneer or partial coverage restoration', category: 'Restorative' },
  { code: 'D2915', label: 'Re-cement or re-bond indirectly fabricated or prefabricated post and core', category: 'Restorative' },
  { code: 'D2920', label: 'Re-cement or re-bond crown', category: 'Restorative' },
  { code: 'D2921', label: 'Reattachment of tooth fragment', category: 'Restorative' },
  { code: 'D2929', label: 'Prefabricated porcelain/ceramic crown — primary tooth', category: 'Restorative' },
  { code: 'D2930', label: 'Prefabricated stainless steel crown — primary tooth', category: 'Restorative' },
  { code: 'D2931', label: 'Prefabricated stainless steel crown — permanent tooth', category: 'Restorative' },
  { code: 'D2932', label: 'Prefabricated resin crown', category: 'Restorative' },
  { code: 'D2933', label: 'Prefabricated tooth-colored crown — primary tooth', category: 'Restorative' },
  { code: 'D2934', label: 'Prefabricated esthetic coated stainless steel crown — primary tooth', category: 'Restorative' },
  { code: 'D2940', label: 'Protective restoration', category: 'Restorative' },
  { code: 'D2941', label: 'Interim therapeutic restoration — primary dentition', category: 'Restorative' },
  { code: 'D2949', label: 'Restorative foundation for an indirect restoration', category: 'Restorative' },
  { code: 'D2950', label: 'Core buildup, including any pins when required', category: 'Restorative' },
  { code: 'D2951', label: 'Pin retention, per tooth, in addition to restoration', category: 'Restorative' },
  { code: 'D2952', label: 'Cast post and core in addition to crown', category: 'Restorative' },
  { code: 'D2953', label: 'Each additional cast post — same tooth', category: 'Restorative' },
  { code: 'D2954', label: 'Prefabricated post and core in addition to crown', category: 'Restorative' },
  { code: 'D2955', label: 'Post removal', category: 'Restorative' },
  { code: 'D2957', label: 'Each additional prefabricated post — same tooth', category: 'Restorative' },
  { code: 'D2960', label: 'Labial veneer — resin laminate — chairside', category: 'Restorative' },
  { code: 'D2961', label: 'Labial veneer — resin laminate — laboratory', category: 'Restorative' },
  { code: 'D2962', label: 'Labial veneer — porcelain laminate — laboratory', category: 'Restorative' },
  { code: 'D2971', label: 'Additional procedures to construct new crown under existing partial denture framework', category: 'Restorative' },
  { code: 'D2980', label: 'Crown repair, by report', category: 'Restorative' },
  { code: 'D2981', label: 'Inlay repair, by report', category: 'Restorative' },
  { code: 'D2982', label: 'Onlay repair, by report', category: 'Restorative' },
  { code: 'D2990', label: 'Resin infiltration of incipient smooth surface lesions', category: 'Restorative' },
];

const endodonticsCodes: DentalCode[] = [
  { code: 'D3110', label: 'Pulp cap — direct', category: 'Endodontics' },
  { code: 'D3120', label: 'Pulp cap — indirect', category: 'Endodontics' },
  { code: 'D3220', label: 'Therapeutic pulpotomy', category: 'Endodontics' },
  { code: 'D3221', label: 'Pulpal debridement, primary and permanent teeth', category: 'Endodontics' },
  { code: 'D3222', label: 'Partial pulpotomy for apexogenesis', category: 'Endodontics' },
  { code: 'D3230', label: 'Pulpal therapy — anterior, primary tooth', category: 'Endodontics' },
  { code: 'D3240', label: 'Pulpal therapy — posterior, primary tooth', category: 'Endodontics' },
  { code: 'D3310', label: 'Endodontic therapy — anterior tooth', category: 'Endodontics' },
  { code: 'D3320', label: 'Endodontic therapy — premolar tooth', category: 'Endodontics' },
  { code: 'D3330', label: 'Endodontic therapy — molar tooth', category: 'Endodontics' },
  { code: 'D3331', label: 'Treatment of root canal — molar (per visit)', category: 'Endodontics' },
  { code: 'D3332', label: 'Incomplete endodontic therapy', category: 'Endodontics' },
  { code: 'D3333', label: 'Internal root repair of perforation defects', category: 'Endodontics' },
  { code: 'D3346', label: 'Retreatment of previous root canal therapy — anterior', category: 'Endodontics' },
  { code: 'D3347', label: 'Retreatment of previous root canal therapy — premolar', category: 'Endodontics' },
  { code: 'D3348', label: 'Retreatment of previous root canal therapy — molar', category: 'Endodontics' },
  { code: 'D3351', label: 'Apexectomy/periradicular surgery — anterior', category: 'Endodontics' },
  { code: 'D3352', label: 'Apexectomy/periradicular surgery — premolar', category: 'Endodontics' },
  { code: 'D3353', label: 'Apexectomy/periradicular surgery — molar', category: 'Endodontics' },
  { code: 'D3410', label: 'Apicoectomy — anterior', category: 'Endodontics' },
  { code: 'D3421', label: 'Apicoectomy — premolar (first root)', category: 'Endodontics' },
  { code: 'D3425', label: 'Apicoectomy — molar (first root)', category: 'Endodontics' },
  { code: 'D3426', label: 'Apicoectomy — molar (each additional root)', category: 'Endodontics' },
  { code: 'D3430', label: 'Retrograde filling — per root', category: 'Endodontics' },
  { code: 'D3450', label: 'Root amputation — per root', category: 'Endodontics' },
  { code: 'D3460', label: 'Endodontic endosseous implant', category: 'Endodontics' },
  { code: 'D3470', label: 'Intentional reimplantation', category: 'Endodontics' },
  { code: 'D3910', label: 'Surgical procedure for isolation of tooth with rubber dam', category: 'Endodontics' },
  { code: 'D3920', label: 'Hemisection (including any root removal), not including root canal therapy', category: 'Endodontics' },
  { code: 'D3950', label: 'Canal preparation and fitting of preformed dowel or post', category: 'Endodontics' },
];

const periodonticsCodes: DentalCode[] = [
  { code: 'D4210', label: 'Gingivectomy or gingivoplasty — four or more contiguous teeth per quadrant', category: 'Periodontics' },
  { code: 'D4211', label: 'Gingivectomy or gingivoplasty — one to three contiguous teeth per quadrant', category: 'Periodontics' },
  { code: 'D4212', label: 'Gingivectomy or gingivoplasty — to allow access for restorative procedure', category: 'Periodontics' },
  { code: 'D4230', label: 'Anatomical crown exposure — four or more contiguous teeth per quadrant', category: 'Periodontics' },
  { code: 'D4231', label: 'Anatomical crown exposure — one to three contiguous teeth per quadrant', category: 'Periodontics' },
  { code: 'D4240', label: 'Gingival flap procedure', category: 'Periodontics' },
  { code: 'D4241', label: 'Gingival flap procedure', category: 'Periodontics' },
  { code: 'D4245', label: 'Apically positioned flap', category: 'Periodontics' },
  { code: 'D4249', label: 'Clinical crown lengthening — hard tissue', category: 'Periodontics' },
  { code: 'D4260', label: 'Osseous surgery — four or more contiguous teeth per quadrant', category: 'Periodontics' },
  { code: 'D4261', label: 'Osseous surgery — one to three contiguous teeth per quadrant', category: 'Periodontics' },
  { code: 'D4263', label: 'Bone replacement graft — retained natural tooth — first site in quadrant', category: 'Periodontics' },
  { code: 'D4264', label: 'Bone replacement graft — retained natural tooth — each additional site', category: 'Periodontics' },
  { code: 'D4265', label: 'Biologic materials to aid in soft and osseous tissue regeneration', category: 'Periodontics' },
  { code: 'D4266', label: 'Guided tissue regeneration — resorbable barrier — per site', category: 'Periodontics' },
  { code: 'D4267', label: 'Guided tissue regeneration — non-resorbable barrier — per site', category: 'Periodontics' },
  { code: 'D4268', label: 'Surgical revision procedure, per tooth', category: 'Periodontics' },
  { code: 'D4270', label: 'Pedicle soft tissue graft procedure', category: 'Periodontics' },
  { code: 'D4271', label: 'Free soft tissue graft procedure', category: 'Periodontics' },
  { code: 'D4273', label: 'Autogenous connective tissue graft procedure — first tooth, implant, or edentulous tooth position', category: 'Periodontics' },
  { code: 'D4274', label: 'Mesial/distal wedge procedure — per tooth', category: 'Periodontics' },
  { code: 'D4275', label: 'Non-autogenous connective tissue graft — first tooth per quadrant', category: 'Periodontics' },
  { code: 'D4276', label: 'Combined connective tissue and double pedicle graft — per tooth', category: 'Periodontics' },
  { code: 'D4277', label: 'Free soft tissue graft — first tooth per quadrant', category: 'Periodontics' },
  { code: 'D4278', label: 'Free soft tissue graft — each additional tooth', category: 'Periodontics' },
  { code: 'D4283', label: 'Autogenous connective tissue graft — each additional tooth', category: 'Periodontics' },
  { code: 'D4285', label: 'Non-autogenous connective tissue graft — each additional tooth', category: 'Periodontics' },
  { code: 'D4320', label: 'Provisional splinting — intracoronal', category: 'Periodontics' },
  { code: 'D4321', label: 'Provisional splinting — extracoronal', category: 'Periodontics' },
  { code: 'D4341', label: 'Periodontal scaling and root planing — four or more teeth per quadrant', category: 'Periodontics' },
  { code: 'D4342', label: 'Periodontal scaling and root planing — one to three teeth per quadrant', category: 'Periodontics' },
  { code: 'D4346', label: 'Scaling in presence of generalized moderate or severe gingival inflammation', category: 'Periodontics' },
  { code: 'D4355', label: 'Full mouth debridement', category: 'Periodontics' },
  { code: 'D4381', label: 'Localized delivery of antimicrobial agents', category: 'Periodontics' },
  { code: 'D4910', label: 'Periodontal maintenance', category: 'Periodontics' },
  { code: 'D4920', label: 'Unscheduled dressing change', category: 'Periodontics' },
  { code: 'D4921', label: 'Gingival irrigation — per quadrant', category: 'Periodontics' },
  { code: 'D4999', label: 'Unspecified periodontal procedure', category: 'Periodontics' },
];

const prosthodonticsRemovableCodes: DentalCode[] = [
  { code: 'D5110', label: 'Complete denture — maxillary', category: 'Prosthodontics (Removable)' },
  { code: 'D5120', label: 'Complete denture — mandibular', category: 'Prosthodontics (Removable)' },
  { code: 'D5130', label: 'Immediate denture — maxillary', category: 'Prosthodontics (Removable)' },
  { code: 'D5140', label: 'Immediate denture — mandibular', category: 'Prosthodontics (Removable)' },
  { code: 'D5211', label: 'Maxillary partial denture — resin base', category: 'Prosthodontics (Removable)' },
  { code: 'D5212', label: 'Mandibular partial denture — resin base', category: 'Prosthodontics (Removable)' },
  { code: 'D5213', label: 'Maxillary partial denture — cast metal framework', category: 'Prosthodontics (Removable)' },
  { code: 'D5214', label: 'Mandibular partial denture — cast metal framework', category: 'Prosthodontics (Removable)' },
  { code: 'D5221', label: 'Immediate maxillary partial denture — resin base', category: 'Prosthodontics (Removable)' },
  { code: 'D5222', label: 'Immediate mandibular partial denture — resin base', category: 'Prosthodontics (Removable)' },
  { code: 'D5223', label: 'Immediate maxillary partial denture — cast metal framework', category: 'Prosthodontics (Removable)' },
  { code: 'D5224', label: 'Immediate mandibular partial denture — cast metal framework', category: 'Prosthodontics (Removable)' },
  { code: 'D5225', label: 'Maxillary partial denture — flexible base', category: 'Prosthodontics (Removable)' },
  { code: 'D5226', label: 'Mandibular partial denture — flexible base', category: 'Prosthodontics (Removable)' },
  { code: 'D5227', label: 'Immediate maxillary partial denture — flexible base', category: 'Prosthodontics (Removable)' },
  { code: 'D5228', label: 'Immediate mandibular partial denture — flexible base', category: 'Prosthodontics (Removable)' },
  { code: 'D5281', label: 'Removable unilateral partial denture — one piece cast metal', category: 'Prosthodontics (Removable)' },
  { code: 'D5410', label: 'Adjust complete denture — maxillary', category: 'Prosthodontics (Removable)' },
  { code: 'D5411', label: 'Adjust complete denture — mandibular', category: 'Prosthodontics (Removable)' },
  { code: 'D5421', label: 'Adjust partial denture — maxillary', category: 'Prosthodontics (Removable)' },
  { code: 'D5422', label: 'Adjust partial denture — mandibular', category: 'Prosthodontics (Removable)' },
  { code: 'D5511', label: 'Repair broken complete denture base, mandibular', category: 'Prosthodontics (Removable)' },
  { code: 'D5512', label: 'Repair broken complete denture base, maxillary', category: 'Prosthodontics (Removable)' },
  { code: 'D5520', label: 'Replace missing or broken teeth — complete denture', category: 'Prosthodontics (Removable)' },
  { code: 'D5611', label: 'Repair resin partial denture base, mandibular', category: 'Prosthodontics (Removable)' },
  { code: 'D5612', label: 'Repair resin partial denture base, maxillary', category: 'Prosthodontics (Removable)' },
  { code: 'D5621', label: 'Repair cast partial framework, mandibular', category: 'Prosthodontics (Removable)' },
  { code: 'D5622', label: 'Repair cast partial framework, maxillary', category: 'Prosthodontics (Removable)' },
  { code: 'D5630', label: 'Repair or replace broken retentive clasping materials — per tooth', category: 'Prosthodontics (Removable)' },
  { code: 'D5640', label: 'Replace broken teeth — per tooth', category: 'Prosthodontics (Removable)' },
  { code: 'D5650', label: 'Add tooth to existing partial denture', category: 'Prosthodontics (Removable)' },
  { code: 'D5660', label: 'Add clasp to existing partial denture — per tooth', category: 'Prosthodontics (Removable)' },
  { code: 'D5670', label: 'Replace all teeth and acrylic on cast metal framework — maxillary', category: 'Prosthodontics (Removable)' },
  { code: 'D5671', label: 'Replace all teeth and acrylic on cast metal framework — mandibular', category: 'Prosthodontics (Removable)' },
  { code: 'D5710', label: 'Rebase complete maxillary denture', category: 'Prosthodontics (Removable)' },
  { code: 'D5711', label: 'Rebase complete mandibular denture', category: 'Prosthodontics (Removable)' },
  { code: 'D5720', label: 'Rebase maxillary partial denture', category: 'Prosthodontics (Removable)' },
  { code: 'D5721', label: 'Rebase mandibular partial denture', category: 'Prosthodontics (Removable)' },
  { code: 'D5730', label: 'Reline complete maxillary denture — chairside', category: 'Prosthodontics (Removable)' },
  { code: 'D5731', label: 'Reline complete mandibular denture — chairside', category: 'Prosthodontics (Removable)' },
  { code: 'D5740', label: 'Reline maxillary partial denture — chairside', category: 'Prosthodontics (Removable)' },
  { code: 'D5741', label: 'Reline mandibular partial denture — chairside', category: 'Prosthodontics (Removable)' },
  { code: 'D5750', label: 'Reline complete maxillary denture — laboratory', category: 'Prosthodontics (Removable)' },
  { code: 'D5751', label: 'Reline complete mandibular denture — laboratory', category: 'Prosthodontics (Removable)' },
  { code: 'D5760', label: 'Reline maxillary partial denture — laboratory', category: 'Prosthodontics (Removable)' },
  { code: 'D5761', label: 'Reline mandibular partial denture — laboratory', category: 'Prosthodontics (Removable)' },
  { code: 'D5810', label: 'Interim complete denture — maxillary', category: 'Prosthodontics (Removable)' },
  { code: 'D5811', label: 'Interim complete denture — mandibular', category: 'Prosthodontics (Removable)' },
  { code: 'D5820', label: 'Interim partial denture — maxillary', category: 'Prosthodontics (Removable)' },
  { code: 'D5821', label: 'Interim partial denture — mandibular', category: 'Prosthodontics (Removable)' },
  { code: 'D5850', label: 'Tissue conditioning, maxillary', category: 'Prosthodontics (Removable)' },
  { code: 'D5851', label: 'Tissue conditioning, mandibular', category: 'Prosthodontics (Removable)' },
  { code: 'D5862', label: 'Precision attachment, by report', category: 'Prosthodontics (Removable)' },
  { code: 'D5863', label: 'Overdenture — complete maxillary', category: 'Prosthodontics (Removable)' },
  { code: 'D5864', label: 'Overdenture — partial maxillary', category: 'Prosthodontics (Removable)' },
  { code: 'D5865', label: 'Overdenture — complete mandibular', category: 'Prosthodontics (Removable)' },
  { code: 'D5866', label: 'Overdenture — partial mandibular', category: 'Prosthodontics (Removable)' },
  { code: 'D5867', label: 'Replacement of replaceable part of semi-precision or precision attachment', category: 'Prosthodontics (Removable)' },
  { code: 'D5875', label: 'Modification of removable prosthesis after implant surgery', category: 'Prosthodontics (Removable)' },
];

const implantServicesCodes: DentalCode[] = [
  { code: 'D6010', label: 'Surgical placement of implant body', category: 'Implant Services' },
  { code: 'D6011', label: 'Second stage implant surgery', category: 'Implant Services' },
  { code: 'D6012', label: 'Surgical placement of interim implant body', category: 'Implant Services' },
  { code: 'D6013', label: 'Surgical placement of mini implant', category: 'Implant Services' },
  { code: 'D6040', label: 'Surgical placement — eposteal implant', category: 'Implant Services' },
  { code: 'D6050', label: 'Surgical placement — transosteal implant', category: 'Implant Services' },
  { code: 'D6051', label: 'Interim abutment', category: 'Implant Services' },
  { code: 'D6052', label: 'Semi-precision attachment abutment', category: 'Implant Services' },
  { code: 'D6055', label: 'Connecting bar — implant supported or abutment supported', category: 'Implant Services' },
  { code: 'D6056', label: 'Prefabricated abutment', category: 'Implant Services' },
  { code: 'D6057', label: 'Custom fabricated abutment', category: 'Implant Services' },
  { code: 'D6058', label: 'Implant-supported porcelain/ceramic crown', category: 'Implant Services' },
  { code: 'D6059', label: 'Implant-supported porcelain fused to metal crown — high noble metal', category: 'Implant Services' },
  { code: 'D6060', label: 'Implant-supported porcelain fused to metal crown — predominantly base metal', category: 'Implant Services' },
  { code: 'D6061', label: 'Implant-supported porcelain fused to metal crown — noble metal', category: 'Implant Services' },
  { code: 'D6062', label: 'Implant-supported cast metal crown — high noble metal', category: 'Implant Services' },
  { code: 'D6063', label: 'Implant-supported cast metal crown — predominantly base metal', category: 'Implant Services' },
  { code: 'D6064', label: 'Implant-supported cast metal crown — noble metal', category: 'Implant Services' },
  { code: 'D6065', label: 'Implant-supported porcelain/ceramic crown', category: 'Implant Services' },
  { code: 'D6066', label: 'Implant crown — porcelain fused to high noble alloys', category: 'Implant Services' },
  { code: 'D6067', label: 'Implant crown — high noble alloys', category: 'Implant Services' },
  { code: 'D6068', label: 'Abutment-supported retainer — porcelain/ceramic', category: 'Implant Services' },
  { code: 'D6069', label: 'Abutment-supported retainer — porcelain fused to metal — high noble metal', category: 'Implant Services' },
  { code: 'D6070', label: 'Abutment-supported retainer — porcelain fused to metal — predominantly base metal', category: 'Implant Services' },
  { code: 'D6071', label: 'Abutment-supported retainer — porcelain fused to metal — noble metal', category: 'Implant Services' },
  { code: 'D6072', label: 'Abutment-supported retainer — cast metal — high noble metal', category: 'Implant Services' },
  { code: 'D6073', label: 'Abutment-supported retainer — cast metal — predominantly base metal', category: 'Implant Services' },
  { code: 'D6074', label: 'Abutment-supported retainer — cast metal — noble metal', category: 'Implant Services' },
  { code: 'D6075', label: 'Implant-supported retainer — porcelain/ceramic', category: 'Implant Services' },
  { code: 'D6076', label: 'Implant-supported retainer — porcelain fused to high noble alloys', category: 'Implant Services' },
  { code: 'D6077', label: 'Implant-supported retainer — cast metal — high noble alloys', category: 'Implant Services' },
  { code: 'D6080', label: 'Implant maintenance procedures', category: 'Implant Services' },
  { code: 'D6081', label: 'Scaling and debridement in the presence of inflammation around implant(s)', category: 'Implant Services' },
  { code: 'D6082', label: 'Implant-supported crown — porcelain fused to predominantly base alloys', category: 'Implant Services' },
  { code: 'D6083', label: 'Implant-supported crown — porcelain fused to noble alloys', category: 'Implant Services' },
  { code: 'D6084', label: 'Implant-supported crown — porcelain fused to titanium and titanium alloys', category: 'Implant Services' },
  { code: 'D6085', label: 'Provisional implant crown', category: 'Implant Services' },
  { code: 'D6086', label: 'Implant-supported crown — predominantly base alloys', category: 'Implant Services' },
  { code: 'D6087', label: 'Implant-supported crown — noble alloys', category: 'Implant Services' },
  { code: 'D6088', label: 'Implant-supported crown — titanium and titanium alloys', category: 'Implant Services' },
  { code: 'D6090', label: 'Repair implant-supported prosthesis, by report', category: 'Implant Services' },
  { code: 'D6091', label: 'Replacement of replaceable part of semi-precision or precision attachment', category: 'Implant Services' },
  { code: 'D6092', label: 'Re-cement or re-bond implant/abutment-supported crown', category: 'Implant Services' },
  { code: 'D6093', label: 'Re-cement or re-bond implant/abutment-supported fixed partial denture', category: 'Implant Services' },
  { code: 'D6094', label: 'Abutment-supported crown — titanium and titanium alloys', category: 'Implant Services' },
  { code: 'D6095', label: 'Repair implant abutment, by report', category: 'Implant Services' },
  { code: 'D6096', label: 'Remove broken implant retaining screw', category: 'Implant Services' },
  { code: 'D6097', label: 'Implant-supported crown — porcelain fused to zirconia', category: 'Implant Services' },
  { code: 'D6098', label: 'Implant-supported retainer — zirconia for fixed partial denture', category: 'Implant Services' },
  { code: 'D6099', label: 'Implant-supported retainer — metal fused to zirconia for fixed partial denture', category: 'Implant Services' },
  { code: 'D6100', label: 'Implant removal, by report', category: 'Implant Services' },
  { code: 'D6101', label: 'Debridement of a peri-implant defect', category: 'Implant Services' },
  { code: 'D6102', label: 'Debridement and osseous contouring of a peri-implant defect', category: 'Implant Services' },
  { code: 'D6103', label: 'Bone graft for repair of peri-implant defect', category: 'Implant Services' },
  { code: 'D6104', label: 'Bone graft at time of implant placement', category: 'Implant Services' },
  { code: 'D6110', label: 'Implant-supported removable denture — maxillary', category: 'Implant Services' },
  { code: 'D6111', label: 'Implant-supported removable denture — mandibular', category: 'Implant Services' },
  { code: 'D6112', label: 'Implant-supported partial denture — maxillary', category: 'Implant Services' },
  { code: 'D6113', label: 'Implant-supported partial denture — mandibular', category: 'Implant Services' },
  { code: 'D6114', label: 'Implant-supported fixed denture — maxillary', category: 'Implant Services' },
  { code: 'D6115', label: 'Implant-supported fixed denture — mandibular', category: 'Implant Services' },
  { code: 'D6116', label: 'Implant-supported partial fixed denture — maxillary', category: 'Implant Services' },
  { code: 'D6117', label: 'Implant-supported partial fixed denture — mandibular', category: 'Implant Services' },
  { code: 'D6118', label: 'Implant-supported interim fixed denture — mandibular', category: 'Implant Services' },
  { code: 'D6119', label: 'Implant-supported interim fixed denture — maxillary', category: 'Implant Services' },
  { code: 'D6120', label: 'Implant-supported retainer — porcelain/ceramic for fixed partial denture', category: 'Implant Services' },
  { code: 'D6121', label: 'Implant-supported retainer — cast metal — predominantly base alloys', category: 'Implant Services' },
  { code: 'D6122', label: 'Implant-supported retainer — cast metal — noble alloys', category: 'Implant Services' },
  { code: 'D6123', label: 'Implant-supported retainer — cast metal — titanium and titanium alloys', category: 'Implant Services' },
  { code: 'D6190', label: 'Radiographic/surgical implant index, by report', category: 'Implant Services' },
  { code: 'D6199', label: 'Unspecified implant procedure, by report', category: 'Implant Services' },
];

const prosthodonticsFixedCodes: DentalCode[] = [
  { code: 'D6205', label: 'Pontic — indirect resin based composite', category: 'Prosthodontics (Fixed)' },
  { code: 'D6210', label: 'Pontic — cast high noble metal', category: 'Prosthodontics (Fixed)' },
  { code: 'D6211', label: 'Pontic — cast predominantly base metal', category: 'Prosthodontics (Fixed)' },
  { code: 'D6212', label: 'Pontic — cast noble metal', category: 'Prosthodontics (Fixed)' },
  { code: 'D6214', label: 'Pontic — titanium and titanium alloys', category: 'Prosthodontics (Fixed)' },
  { code: 'D6240', label: 'Pontic — porcelain fused to high noble metal', category: 'Prosthodontics (Fixed)' },
  { code: 'D6241', label: 'Pontic — porcelain fused to predominantly base metal', category: 'Prosthodontics (Fixed)' },
  { code: 'D6242', label: 'Pontic — porcelain fused to noble metal', category: 'Prosthodontics (Fixed)' },
  { code: 'D6243', label: 'Pontic — porcelain fused to titanium and titanium alloys', category: 'Prosthodontics (Fixed)' },
  { code: 'D6245', label: 'Pontic — porcelain/ceramic', category: 'Prosthodontics (Fixed)' },
  { code: 'D6250', label: 'Pontic — resin with high noble metal', category: 'Prosthodontics (Fixed)' },
  { code: 'D6251', label: 'Pontic — resin with predominantly base metal', category: 'Prosthodontics (Fixed)' },
  { code: 'D6252', label: 'Pontic — resin with noble metal', category: 'Prosthodontics (Fixed)' },
  { code: 'D6253', label: 'Provisional pontic', category: 'Prosthodontics (Fixed)' },
  { code: 'D6545', label: 'Retainer — cast metal for resin-bonded fixed prosthesis', category: 'Prosthodontics (Fixed)' },
  { code: 'D6548', label: 'Retainer — porcelain/ceramic for resin-bonded fixed prosthesis', category: 'Prosthodontics (Fixed)' },
  { code: 'D6549', label: 'Resin-retained retainer — for resin-bonded fixed prosthesis', category: 'Prosthodontics (Fixed)' },
  { code: 'D6600', label: 'Retainer inlay — metallic — two surfaces', category: 'Prosthodontics (Fixed)' },
  { code: 'D6601', label: 'Retainer inlay — metallic — three or more surfaces', category: 'Prosthodontics (Fixed)' },
  { code: 'D6602', label: 'Retainer inlay — cast high noble metal — two surfaces', category: 'Prosthodontics (Fixed)' },
  { code: 'D6603', label: 'Retainer inlay — cast high noble metal — three or more surfaces', category: 'Prosthodontics (Fixed)' },
  { code: 'D6604', label: 'Retainer inlay — cast predominantly base metal — two surfaces', category: 'Prosthodontics (Fixed)' },
  { code: 'D6605', label: 'Retainer inlay — cast predominantly base metal — three or more surfaces', category: 'Prosthodontics (Fixed)' },
  { code: 'D6606', label: 'Retainer inlay — cast noble metal — two surfaces', category: 'Prosthodontics (Fixed)' },
  { code: 'D6607', label: 'Retainer inlay — cast noble metal — three or more surfaces', category: 'Prosthodontics (Fixed)' },
  { code: 'D6608', label: 'Retainer onlay — porcelain/ceramic — two surfaces', category: 'Prosthodontics (Fixed)' },
  { code: 'D6609', label: 'Retainer onlay — porcelain/ceramic — three or more surfaces', category: 'Prosthodontics (Fixed)' },
  { code: 'D6610', label: 'Retainer onlay — cast high noble metal — two surfaces', category: 'Prosthodontics (Fixed)' },
  { code: 'D6611', label: 'Retainer onlay — cast high noble metal — three or more surfaces', category: 'Prosthodontics (Fixed)' },
  { code: 'D6612', label: 'Retainer onlay — cast predominantly base metal — two surfaces', category: 'Prosthodontics (Fixed)' },
  { code: 'D6613', label: 'Retainer onlay — cast predominantly base metal — three or more surfaces', category: 'Prosthodontics (Fixed)' },
  { code: 'D6614', label: 'Retainer onlay — cast noble metal — two surfaces', category: 'Prosthodontics (Fixed)' },
  { code: 'D6615', label: 'Retainer onlay — cast noble metal — three or more surfaces', category: 'Prosthodontics (Fixed)' },
  { code: 'D6624', label: 'Retainer inlay — titanium', category: 'Prosthodontics (Fixed)' },
  { code: 'D6634', label: 'Retainer onlay — titanium', category: 'Prosthodontics (Fixed)' },
  { code: 'D6710', label: 'Retainer crown — indirect resin based composite', category: 'Prosthodontics (Fixed)' },
  { code: 'D6720', label: 'Retainer crown — resin with high noble metal', category: 'Prosthodontics (Fixed)' },
  { code: 'D6721', label: 'Retainer crown — resin with predominantly base metal', category: 'Prosthodontics (Fixed)' },
  { code: 'D6722', label: 'Retainer crown — resin with noble metal', category: 'Prosthodontics (Fixed)' },
  { code: 'D6740', label: 'Retainer crown — porcelain/ceramic', category: 'Prosthodontics (Fixed)' },
  { code: 'D6750', label: 'Retainer crown — porcelain fused to high noble metal', category: 'Prosthodontics (Fixed)' },
  { code: 'D6751', label: 'Retainer crown — porcelain fused to predominantly base metal', category: 'Prosthodontics (Fixed)' },
  { code: 'D6752', label: 'Retainer crown — porcelain fused to noble metal', category: 'Prosthodontics (Fixed)' },
  { code: 'D6753', label: 'Retainer crown — porcelain fused to titanium and titanium alloys', category: 'Prosthodontics (Fixed)' },
  { code: 'D6780', label: 'Retainer crown — 3/4 cast high noble metal', category: 'Prosthodontics (Fixed)' },
  { code: 'D6781', label: 'Retainer crown — 3/4 cast predominantly base metal', category: 'Prosthodontics (Fixed)' },
  { code: 'D6782', label: 'Retainer crown — 3/4 cast noble metal', category: 'Prosthodontics (Fixed)' },
  { code: 'D6783', label: 'Retainer crown — 3/4 porcelain/ceramic', category: 'Prosthodontics (Fixed)' },
  { code: 'D6790', label: 'Retainer crown — full cast high noble metal', category: 'Prosthodontics (Fixed)' },
  { code: 'D6791', label: 'Retainer crown — full cast predominantly base metal', category: 'Prosthodontics (Fixed)' },
  { code: 'D6792', label: 'Retainer crown — full cast noble metal', category: 'Prosthodontics (Fixed)' },
  { code: 'D6794', label: 'Retainer crown — titanium and titanium alloys', category: 'Prosthodontics (Fixed)' },
  { code: 'D6920', label: 'Connector bar', category: 'Prosthodontics (Fixed)' },
  { code: 'D6930', label: 'Re-cement or re-bond fixed partial denture', category: 'Prosthodontics (Fixed)' },
  { code: 'D6940', label: 'Stress breaker', category: 'Prosthodontics (Fixed)' },
  { code: 'D6950', label: 'Precision attachment', category: 'Prosthodontics (Fixed)' },
  { code: 'D6980', label: 'Fixed partial denture repair, by report', category: 'Prosthodontics (Fixed)' },
  { code: 'D6985', label: 'Pediatric partial denture, fixed', category: 'Prosthodontics (Fixed)' },
  { code: 'D6999', label: 'Unspecified fixed prosthodontic procedure, by report', category: 'Prosthodontics (Fixed)' },
];

const oralSurgeryCodes: DentalCode[] = [
  { code: 'D7110', label: 'Extraction — coronal remnants', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7111', label: 'Extraction — coronal remnants', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7140', label: 'Extraction — erupted tooth or exposed root', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7210', label: 'Surgical extraction of erupted tooth', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7220', label: 'Removal of impacted tooth — soft tissue', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7230', label: 'Removal of impacted tooth — partially bony', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7240', label: 'Removal of impacted tooth — completely bony', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7241', label: 'Removal of impacted tooth — completely bony, with unusual surgical complications', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7250', label: 'Removal of residual tooth roots', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7251', label: 'Coronectomy', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7260', label: 'Oroantral fistula closure', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7261', label: 'Primary closure of a sinus perforation', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7270', label: 'Tooth reimplantation', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7272', label: 'Tooth transplantation', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7280', label: 'Surgical access of an unerupted tooth', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7282', label: 'Mobilization of erupted or malpositioned tooth', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7283', label: 'Placement of device to facilitate eruption of impacted tooth', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7285', label: 'Biopsy of oral tissue — hard (bone, tooth)', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7286', label: 'Biopsy of oral tissue — soft', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7287', label: 'Exfoliative cytological sample collection', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7288', label: 'Brush biopsy — transepithelial sample collection', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7290', label: 'Surgical repositioning of teeth', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7291', label: 'Transseptal fiberotomy/supra crestal fiberotomy', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7292', label: 'Placement of temporary anchorage device', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7293', label: 'Placement of temporary anchorage device', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7294', label: 'Removal of temporary anchorage device', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7295', label: 'Bone harvesting for autogenous grafting procedure', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7296', label: 'Corticotomy — one to three teeth or tooth spaces', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7297', label: 'Corticotomy — four or more teeth or tooth spaces', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7310', label: 'Alveoloplasty in conjunction with extractions — four or more teeth per quadrant', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7311', label: 'Alveoloplasty in conjunction with extractions — one to three teeth per quadrant', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7320', label: 'Alveoloplasty not in conjunction with extractions — four or more teeth per quadrant', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7321', label: 'Alveoloplasty not in conjunction with extractions — one to three teeth per quadrant', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7340', label: 'Vestibuloplasty — ridge extension', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7350', label: 'Vestibuloplasty — ridge extension with soft tissue grafts', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7410', label: 'Excision of benign lesion — up to 1.25 cm', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7411', label: 'Excision of benign lesion — greater than 1.25 cm', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7412', label: 'Excision of benign lesion complicated', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7413', label: 'Excision of malignant lesion — up to 1.25 cm', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7414', label: 'Excision of malignant lesion — greater than 1.25 cm', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7415', label: 'Excision of malignant lesion complicated', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7440', label: 'Excision of malignant tumor — up to 1.25 cm', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7441', label: 'Excision of malignant tumor — greater than 1.25 cm', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7450', label: 'Removal of benign odontogenic cyst or tumor', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7451', label: 'Removal of benign odontogenic cyst or tumor — complicated', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7460', label: 'Removal of benign nonodontogenic cyst or tumor', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7461', label: 'Removal of benign nonodontogenic cyst or tumor — complicated', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7465', label: 'Destruction of lesion(s) by physical or chemical method, by report', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7471', label: 'Removal of lateral exostosis', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7472', label: 'Removal of torus palatinus', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7473', label: 'Removal of torus mandibularis', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7485', label: 'Reduction of osseous tuberosity', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7490', label: 'Radical resection of maxilla or mandible', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7510', label: 'Incision and drainage of abscess — intraoral soft tissue', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7511', label: 'Incision and drainage of abscess — intraoral soft tissue — complicated', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7520', label: 'Incision and drainage of abscess — extraoral soft tissue', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7521', label: 'Incision and drainage of abscess — extraoral soft tissue — complicated', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7530', label: 'Removal of foreign body from mucosa, skin, or subcutaneous alveolar tissue', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7540', label: 'Removal of reaction-producing foreign bodies — musculoskeletal system', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7550', label: 'Partial ostectomy/sequestrectomy for removal of non-vital bone', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7560', label: 'Maxillary sinusotomy for removal of tooth fragment or foreign body', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7610', label: 'Maxilla — open reduction', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7620', label: 'Maxilla — closed reduction', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7630', label: 'Mandible — open reduction', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7640', label: 'Mandible — closed reduction', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7650', label: 'Malar and/or zygomatic arch — open reduction', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7660', label: 'Malar and/or zygomatic arch — closed reduction', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7670', label: 'Alveolus — closed reduction', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7671', label: 'Alveolus — open reduction', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7680', label: 'Facial bones — complicated reduction with fixation and multiple surgical approaches', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7710', label: 'Maxilla — open reduction', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7720', label: 'Maxilla — closed reduction', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7730', label: 'Mandible — open reduction', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7740', label: 'Mandible — closed reduction', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7750', label: 'Malar and/or zygomatic arch — open reduction', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7760', label: 'Malar and/or zygomatic arch — closed reduction', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7770', label: 'Alveolus — open reduction', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7771', label: 'Alveolus — closed reduction', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7780', label: 'Facial bones — complicated reduction with fixation and multiple surgical approaches', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7810', label: 'Open reduction of dislocation', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7820', label: 'Closed reduction of dislocation', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7830', label: 'Manipulation under anesthesia', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7840', label: 'Condylectomy', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7850', label: 'Surgical discectomy', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7852', label: 'Disc repair', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7854', label: 'Synovectomy', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7856', label: 'Myotomy', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7858', label: 'Joint reconstruction', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7860', label: 'Arthroscopy', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7865', label: 'Arthroplasty', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7870', label: 'Arthrocentesis', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7872', label: 'Arthroscopy — diagnosis', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7873', label: 'Arthroscopy — surgical — lavage and lysis of adhesions', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7874', label: 'Arthroscopy — surgical — disc repositioning and stabilization', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7875', label: 'Arthroscopy — surgical — synovectomy', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7876', label: 'Arthroscopy — surgical — discectomy', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7877', label: 'Arthroscopy — surgical — debridement', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7880', label: 'Occlusal orthotic device, by report', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7881', label: 'Occlusal orthotic device adjustment', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7899', label: 'Unspecified TMD therapy, by report', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7910', label: 'Suture of recent small wounds up to 5 cm', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7911', label: 'Complicated suture — up to 5 cm', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7912', label: 'Complicated suture — greater than 5 cm', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7920', label: 'Skin graft', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7921', label: 'Collection and application of autogenous blood concentrate product', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7922', label: 'Placement of intraoral bone matrix material', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7940', label: 'Osteoplasty — for orthognathic deformities', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7941', label: 'Osteotomy — mandibular rami', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7943', label: 'Osteotomy — mandibular rami with bone graft', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7944', label: 'Osteotomy — segmented or subapical — per segment or quadrant', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7945', label: 'Osteotomy — body of mandible', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7946', label: 'LeFort I (maxilla — total)', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7947', label: 'LeFort I (maxilla — segmented)', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7948', label: 'LeFort II or LeFort III', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7949', label: 'Osteotomy — other, by report', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7950', label: 'Osseous, osteoperiosteal, or cartilage graft of the mandible', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7951', label: 'Sinus augmentation with bone or bone substitutes', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7952', label: 'Sinus augmentation — crestal or internal approach', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7953', label: 'Bone replacement graft for ridge preservation — per site', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7954', label: 'Bone replacement graft — for ridge augmentation — per site', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7955', label: 'Repair of maxillofacial soft and/or hard tissue defect', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7960', label: 'Frenulectomy', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7963', label: 'Frenuloplasty', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7970', label: 'Excision of hyperplastic tissue — per arch', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7971', label: 'Excision of pericoronal gingiva', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7972', label: 'Surgical reduction of fibrous tuberosity', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7979', label: 'Non-surgical sialolithotomy', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7980', label: 'Sialolithotomy', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7981', label: 'Excision of salivary gland, by report', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7982', label: 'Sialodochoplasty', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7983', label: 'Closure of salivary fistula', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7990', label: 'Emergency tracheotomy', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7991', label: 'Coronoidectomy', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7995', label: 'Synthetic graft — mandible or facial bones, by report', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7996', label: 'Implant — mandible for augmentation purposes', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7997', label: 'Appliance removal (not including removal of a fixed space maintainer)', category: 'Oral & Maxillofacial Surgery' },
  { code: 'D7999', label: 'Unspecified oral surgery procedure, by report', category: 'Oral & Maxillofacial Surgery' },
];

const orthodonticsCodes: DentalCode[] = [
  { code: 'D8010', label: 'Limited orthodontic treatment — primary dentition', category: 'Orthodontics' },
  { code: 'D8020', label: 'Limited orthodontic treatment — transitional dentition', category: 'Orthodontics' },
  { code: 'D8030', label: 'Limited orthodontic treatment — adolescent dentition', category: 'Orthodontics' },
  { code: 'D8040', label: 'Limited orthodontic treatment — adult dentition', category: 'Orthodontics' },
  { code: 'D8050', label: 'Interceptive orthodontic treatment — primary dentition', category: 'Orthodontics' },
  { code: 'D8060', label: 'Interceptive orthodontic treatment — transitional dentition', category: 'Orthodontics' },
  { code: 'D8070', label: 'Comprehensive orthodontic treatment — transitional dentition', category: 'Orthodontics' },
  { code: 'D8080', label: 'Comprehensive orthodontic treatment — adolescent dentition', category: 'Orthodontics' },
  { code: 'D8090', label: 'Comprehensive orthodontic treatment — adult dentition', category: 'Orthodontics' },
  { code: 'D8210', label: 'Removable appliance therapy', category: 'Orthodontics' },
  { code: 'D8220', label: 'Fixed appliance therapy', category: 'Orthodontics' },
  { code: 'D8660', label: 'Pre-orthodontic treatment examination', category: 'Orthodontics' },
  { code: 'D8670', label: 'Periodic orthodontic treatment visit', category: 'Orthodontics' },
  { code: 'D8680', label: 'Orthodontic retention', category: 'Orthodontics' },
  { code: 'D8681', label: 'Removable orthodontic retainer adjustment', category: 'Orthodontics' },
  { code: 'D8695', label: 'Removal of fixed orthodontic appliances for reasons other than the completion of treatment', category: 'Orthodontics' },
  { code: 'D8696', label: 'Repair of orthodontic appliance, by report', category: 'Orthodontics' },
  { code: 'D8697', label: 'Re-cement or re-bond fixed retainer — per tooth', category: 'Orthodontics' },
  { code: 'D8698', label: 'Re-cement or re-bond fixed retainer — per arch', category: 'Orthodontics' },
  { code: 'D8699', label: 'Repair of fixed retainer, by report', category: 'Orthodontics' },
  { code: 'D8701', label: 'Repair of fixed retainer', category: 'Orthodontics' },
  { code: 'D8702', label: 'Removal of fixed retainer', category: 'Orthodontics' },
  { code: 'D8703', label: 'Replacement of lost or broken retainer', category: 'Orthodontics' },
  { code: 'D8999', label: 'Unspecified orthodontic procedure, by report', category: 'Orthodontics' },
];

const adjunctiveGeneralCodes: DentalCode[] = [
  { code: 'D9110', label: 'Palliative (emergency) treatment of dental pain', category: 'Adjunctive General Services' },
  { code: 'D9120', label: 'Fixed partial denture sectioning', category: 'Adjunctive General Services' },
  { code: 'D9130', label: 'Temporomandibular joint dysfunction — non-invasive physical therapies', category: 'Adjunctive General Services' },
  { code: 'D9210', label: 'Local anesthesia — not in conjunction with operative or surgical procedures', category: 'Adjunctive General Services' },
  { code: 'D9211', label: 'Regional block anesthesia', category: 'Adjunctive General Services' },
  { code: 'D9212', label: 'Trigeminal division block anesthesia', category: 'Adjunctive General Services' },
  { code: 'D9215', label: 'Local anesthesia', category: 'Adjunctive General Services' },
  { code: 'D9219', label: 'Evaluation for moderate sedation', category: 'Adjunctive General Services' },
  { code: 'D9220', label: 'Deep sedation/general anesthesia — first 15 minutes', category: 'Adjunctive General Services' },
  { code: 'D9221', label: 'Deep sedation/general anesthesia — each subsequent 15-minute increment', category: 'Adjunctive General Services' },
  { code: 'D9222', label: 'Deep sedation/general anesthesia — first 30 minutes', category: 'Adjunctive General Services' },
  { code: 'D9223', label: 'Deep sedation/general anesthesia — each subsequent 15-minute increment', category: 'Adjunctive General Services' },
  { code: 'D9230', label: 'Inhalation of nitrous oxide/anxiolysis', category: 'Adjunctive General Services' },
  { code: 'D9239', label: 'Intravenous moderate (conscious) sedation/analgesia — first 15 minutes', category: 'Adjunctive General Services' },
  { code: 'D9243', label: 'Intravenous moderate (conscious) sedation/analgesia — each subsequent 15-minute increment', category: 'Adjunctive General Services' },
  { code: 'D9248', label: 'Non-intravenous conscious sedation', category: 'Adjunctive General Services' },
  { code: 'D9310', label: 'Consultation — diagnostic service provided by dentist other than requesting dentist', category: 'Adjunctive General Services' },
  { code: 'D9311', label: 'Consultation with a medical health care professional', category: 'Adjunctive General Services' },
  { code: 'D9410', label: 'House/extended care facility call', category: 'Adjunctive General Services' },
  { code: 'D9420', label: 'Hospital or ambulatory surgical center call', category: 'Adjunctive General Services' },
  { code: 'D9430', label: 'Office visit for observation', category: 'Adjunctive General Services' },
  { code: 'D9440', label: 'Office visit — after regularly scheduled hours', category: 'Adjunctive General Services' },
  { code: 'D9450', label: 'Case presentation, detailed and extensive treatment planning', category: 'Adjunctive General Services' },
  { code: 'D9610', label: 'Injection of therapeutic drug', category: 'Adjunctive General Services' },
  { code: 'D9612', label: 'Tray delivery of fluoride', category: 'Adjunctive General Services' },
  { code: 'D9613', label: 'Injection of therapeutic drug — each subsequent injection', category: 'Adjunctive General Services' },
  { code: 'D9620', label: 'Injection of tetanus toxoid', category: 'Adjunctive General Services' },
  { code: 'D9630', label: 'Drugs or medicaments dispensed in the office for home use', category: 'Adjunctive General Services' },
  { code: 'D9910', label: 'Application of desensitizing medicament', category: 'Adjunctive General Services' },
  { code: 'D9911', label: 'Application of desensitizing resin', category: 'Adjunctive General Services' },
  { code: 'D9920', label: 'Behavior management, by report', category: 'Adjunctive General Services' },
  { code: 'D9930', label: 'Treatment of complications — post-surgical, by report', category: 'Adjunctive General Services' },
  { code: 'D9931', label: 'Treatment of postoperative complications — not elsewhere classified', category: 'Adjunctive General Services' },
  { code: 'D9932', label: 'Cleaning and inspection of removable complete denture, maxillary', category: 'Adjunctive General Services' },
  { code: 'D9933', label: 'Cleaning and inspection of removable complete denture, mandibular', category: 'Adjunctive General Services' },
  { code: 'D9934', label: 'Cleaning and inspection of removable partial denture, maxillary', category: 'Adjunctive General Services' },
  { code: 'D9935', label: 'Cleaning and inspection of removable partial denture, mandibular', category: 'Adjunctive General Services' },
  { code: 'D9940', label: 'Occlusal guard', category: 'Adjunctive General Services' },
  { code: 'D9941', label: 'Fabrication of athletic mouthguard', category: 'Adjunctive General Services' },
  { code: 'D9942', label: 'Repair and/or reline of occlusal guard', category: 'Adjunctive General Services' },
  { code: 'D9943', label: 'Occlusal guard adjustment', category: 'Adjunctive General Services' },
  { code: 'D9944', label: 'Occlusal guard — hard appliance, full arch', category: 'Adjunctive General Services' },
  { code: 'D9945', label: 'Occlusal guard — soft appliance, full arch', category: 'Adjunctive General Services' },
  { code: 'D9946', label: 'Occlusal guard — hard appliance, partial arch', category: 'Adjunctive General Services' },
  { code: 'D9947', label: 'Custom sleep apnea appliance', category: 'Adjunctive General Services' },
  { code: 'D9948', label: 'Adjustment of custom sleep apnea appliance', category: 'Adjunctive General Services' },
  { code: 'D9950', label: 'Occlusion analysis — mounted case', category: 'Adjunctive General Services' },
  { code: 'D9951', label: 'Occlusal adjustment — limited', category: 'Adjunctive General Services' },
  { code: 'D9952', label: 'Occlusal adjustment — complete', category: 'Adjunctive General Services' },
  { code: 'D9953', label: 'Recontouring of teeth, by report', category: 'Adjunctive General Services' },
  { code: 'D9954', label: 'Recontouring of existing crown, by report', category: 'Adjunctive General Services' },
  { code: 'D9955', label: 'Recontouring of existing dental material, by report', category: 'Adjunctive General Services' },
  { code: 'D9961', label: 'Duplicate/copy patient records', category: 'Adjunctive General Services' },
  { code: 'D9970', label: 'Enamel microabrasion', category: 'Adjunctive General Services' },
  { code: 'D9971', label: 'Odontoplasty — one to two teeth', category: 'Adjunctive General Services' },
  { code: 'D9972', label: 'External bleaching — per arch', category: 'Adjunctive General Services' },
  { code: 'D9973', label: 'External bleaching — per tooth', category: 'Adjunctive General Services' },
  { code: 'D9974', label: 'Internal bleaching — per tooth', category: 'Adjunctive General Services' },
  { code: 'D9975', label: 'External bleaching for home application', category: 'Adjunctive General Services' },
  { code: 'D9976', label: 'Rehydration of bleached teeth', category: 'Adjunctive General Services' },
  { code: 'D9977', label: 'Desensitization of bleached teeth', category: 'Adjunctive General Services' },
  { code: 'D9985', label: 'Sales tax', category: 'Adjunctive General Services' },
  { code: 'D9986', label: 'Missed appointment', category: 'Adjunctive General Services' },
  { code: 'D9987', label: 'Cancelled appointment', category: 'Adjunctive General Services' },
  { code: 'D9990', label: 'Certified translation or sign language services — per visit', category: 'Adjunctive General Services' },
  { code: 'D9991', label: 'Dental case management — addressing appointment compliance barriers', category: 'Adjunctive General Services' },
  { code: 'D9992', label: 'Dental case management — care coordination', category: 'Adjunctive General Services' },
  { code: 'D9993', label: 'Dental case management — motivational interviewing', category: 'Adjunctive General Services' },
  { code: 'D9994', label: 'Dental case management — patient education to improve oral health literacy', category: 'Adjunctive General Services' },
  { code: 'D9995', label: 'Teledentistry — synchronous', category: 'Adjunctive General Services' },
  { code: 'D9996', label: 'Teledentistry — asynchronous', category: 'Adjunctive General Services' },
  { code: 'D9997', label: 'Dental case management — patients with special health care needs', category: 'Adjunctive General Services' },
  { code: 'D9999', label: 'Unspecified adjunctive procedure, by report', category: 'Adjunctive General Services' },
];

export const DENTAL_CODE_CATEGORIES: DentalCodeCategory[] = [
  { name: 'Diagnostic', range: 'D0100-D0999', codes: diagnosticCodes },
  { name: 'Preventive', range: 'D1000-D1999', codes: preventiveCodes },
  { name: 'Restorative', range: 'D2000-D2999', codes: restorativeCodes },
  { name: 'Endodontics', range: 'D3000-D3999', codes: endodonticsCodes },
  { name: 'Periodontics', range: 'D4000-D4999', codes: periodonticsCodes },
  { name: 'Prosthodontics (Removable)', range: 'D5000-D5899', codes: prosthodonticsRemovableCodes },
  { name: 'Implant Services', range: 'D6000-D6199', codes: implantServicesCodes },
  { name: 'Prosthodontics (Fixed)', range: 'D6200-D6999', codes: prosthodonticsFixedCodes },
  { name: 'Oral & Maxillofacial Surgery', range: 'D7000-D7999', codes: oralSurgeryCodes },
  { name: 'Orthodontics', range: 'D8000-D8999', codes: orthodonticsCodes },
  { name: 'Adjunctive General Services', range: 'D9000-D9999', codes: adjunctiveGeneralCodes },
];

export const DENTAL_CODES: DentalCode[] = DENTAL_CODE_CATEGORIES.flatMap(
  (category) => category.codes,
);
